-- F.w 研究所数据库补丁 07：观鸟台第一版
-- 使用方法：Supabase SQL Editor 执行。可重复运行。

create table if not exists public.bird_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  content text not null,
  display_mode text not null default 'profile',
  pen_name text,
  images jsonb not null default '[]'::jsonb,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bird_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.bird_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'bird_posts_title_length_check'
      and conrelid = 'public.bird_posts'::regclass
  ) then
    alter table public.bird_posts
      add constraint bird_posts_title_length_check
      check (char_length(title) between 2 and 80);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'bird_posts_content_length_check'
      and conrelid = 'public.bird_posts'::regclass
  ) then
    alter table public.bird_posts
      add constraint bird_posts_content_length_check
      check (char_length(content) between 1 and 5000);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'bird_posts_display_mode_check'
      and conrelid = 'public.bird_posts'::regclass
  ) then
    alter table public.bird_posts
      add constraint bird_posts_display_mode_check
      check (display_mode in ('profile','anonymous','pen_name'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'bird_posts_pen_name_check'
      and conrelid = 'public.bird_posts'::regclass
  ) then
    alter table public.bird_posts
      add constraint bird_posts_pen_name_check
      check (
        (display_mode = 'pen_name' and char_length(trim(coalesce(pen_name, ''))) between 2 and 20)
        or
        (display_mode in ('profile','anonymous') and pen_name is null)
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'bird_posts_images_count_check'
      and conrelid = 'public.bird_posts'::regclass
  ) then
    alter table public.bird_posts
      add constraint bird_posts_images_count_check
      check (jsonb_typeof(images) = 'array' and jsonb_array_length(images) <= 20);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'bird_comments_content_length_check'
      and conrelid = 'public.bird_comments'::regclass
  ) then
    alter table public.bird_comments
      add constraint bird_comments_content_length_check
      check (char_length(content) between 1 and 500);
  end if;
end
$$;

create index if not exists bird_posts_created_at_idx
  on public.bird_posts(created_at desc);

create index if not exists bird_comments_post_id_idx
  on public.bird_comments(post_id);

create or replace function public.fw_touch_bird_post_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists bird_posts_touch_updated_at on public.bird_posts;
create trigger bird_posts_touch_updated_at
  before update on public.bird_posts
  for each row execute function public.fw_touch_bird_post_updated_at();

alter table public.bird_posts enable row level security;
alter table public.bird_comments enable row level security;

drop policy if exists "bird_posts_select_public" on public.bird_posts;
create policy "bird_posts_select_public"
  on public.bird_posts
  for select
  using (is_deleted = false);

drop policy if exists "bird_posts_insert_user" on public.bird_posts;
create policy "bird_posts_insert_user"
  on public.bird_posts
  for insert
  to authenticated
  with check (auth.uid() = user_id and public.is_not_banned());

drop policy if exists "bird_posts_update_admin" on public.bird_posts;
create policy "bird_posts_update_admin"
  on public.bird_posts
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "bird_comments_select_public" on public.bird_comments;
create policy "bird_comments_select_public"
  on public.bird_comments
  for select
  using (is_deleted = false);

drop policy if exists "bird_comments_insert_user" on public.bird_comments;
create policy "bird_comments_insert_user"
  on public.bird_comments
  for insert
  to authenticated
  with check (
    auth.uid() = user_id
    and public.is_not_banned()
    and exists (
      select 1
      from public.bird_posts p
      where p.id = post_id
        and p.is_deleted = false
    )
  );

drop policy if exists "bird_comments_update_admin" on public.bird_comments;
create policy "bird_comments_update_admin"
  on public.bird_comments
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create or replace function public.fw_delete_own_bird_post(p_post_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.bird_posts
  set is_deleted = true
  where id = p_post_id
    and user_id = auth.uid()
    and is_deleted = false;

  if not found then
    raise exception '只能删除自己的观鸟台帖子';
  end if;
end;
$$;

create or replace function public.fw_delete_own_bird_comment(p_comment_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.bird_comments
  set is_deleted = true
  where id = p_comment_id
    and user_id = auth.uid()
    and is_deleted = false;

  if not found then
    raise exception '只能删除自己的观鸟台评论';
  end if;
end;
$$;

revoke all on function public.fw_delete_own_bird_post(bigint) from public;
revoke all on function public.fw_delete_own_bird_comment(bigint) from public;
grant execute on function public.fw_delete_own_bird_post(bigint) to authenticated;
grant execute on function public.fw_delete_own_bird_comment(bigint) to authenticated;

grant select on public.bird_posts to anon, authenticated;
grant insert, update on public.bird_posts to authenticated;
grant select on public.bird_comments to anon, authenticated;
grant insert, update on public.bird_comments to authenticated;

-- identity 自增主键需要序列权限；否则普通登录用户插入时可能报 permission denied for sequence。
grant usage, select on all sequences in schema public to authenticated;
