-- F.w 研究所 学术研讨投票区
-- 使用方法：Supabase Dashboard -> SQL Editor -> New query -> 粘贴全文 -> Run
-- 只新增投票相关表和 RPC，不修改旧聊天室表，也不复用 chat_messages。
-- 统计公开，个人投票选择不公开：前端只通过聚合 RPC 读取票数，通过个人 RPC 读取自己的选择。

create extension if not exists "pgcrypto";

create table if not exists public.polls (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(btrim(title)) between 1 and 120),
  is_official boolean not null default false,
  ends_at timestamptz not null default (now() + interval '7 days'),
  closed_at timestamptz,
  conclusion text,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.poll_options (
  id bigint generated by default as identity primary key,
  poll_id bigint not null references public.polls(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  label text not null check (char_length(btrim(label)) between 1 and 80),
  source text not null default 'user' check (source in ('initial','user')),
  created_at timestamptz not null default now(),
  unique (poll_id, id)
);

create table if not exists public.poll_votes (
  id bigint generated by default as identity primary key,
  poll_id bigint not null references public.polls(id) on delete cascade,
  option_id bigint not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (poll_id, user_id),
  foreign key (poll_id, option_id) references public.poll_options(poll_id, id) on delete cascade
);

create index if not exists polls_created_at_idx on public.polls(created_at desc);
create index if not exists polls_official_idx on public.polls(is_official desc, created_at desc);
create index if not exists poll_options_poll_id_idx on public.poll_options(poll_id);
create index if not exists poll_votes_poll_id_idx on public.poll_votes(poll_id);
create unique index if not exists poll_options_unique_label_idx
  on public.poll_options(poll_id, lower(btrim(label)));
create unique index if not exists poll_options_one_user_added_idx
  on public.poll_options(poll_id, user_id)
  where source = 'user' and user_id is not null;

create or replace function public.fw_poll_day_start()
returns timestamptz
language sql
stable
as $$
  select date_trunc('day', now() at time zone 'Asia/Shanghai') at time zone 'Asia/Shanghai';
$$;

create or replace function public.fw_require_poll_user()
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception '请先登录。';
  end if;

  if not exists (
    select 1
    from public.profiles
    where id = v_uid
      and is_banned = false
  ) then
    raise exception '这个账号当前不能参与投票研究。';
  end if;

  return v_uid;
end;
$$;

create or replace function public.fw_my_poll_daily_count()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_day_start timestamptz := public.fw_poll_day_start();
  v_count integer := 0;
begin
  if v_uid is null then
    return 0;
  end if;

  select count(*)::integer
  into v_count
  from public.polls
  where user_id = v_uid
    and is_deleted = false
    and created_at >= v_day_start
    and created_at < v_day_start + interval '1 day';

  return coalesce(v_count, 0);
end;
$$;

create or replace function public.fw_create_poll(
  p_title text,
  p_options text[],
  p_is_official boolean default false
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := public.fw_require_poll_user();
  v_title text := btrim(coalesce(p_title, ''));
  v_options text[];
  v_daily_count integer := 0;
  v_poll_id bigint;
  v_is_admin boolean := false;
  v_day_start timestamptz := public.fw_poll_day_start();
begin
  select coalesce(array_agg(btrim(option_text) order by ord), array[]::text[])
  into v_options
  from unnest(coalesce(p_options, array[]::text[])) with ordinality as raw(option_text, ord)
  where btrim(coalesce(option_text, '')) <> '';

  if char_length(v_title) < 1 or char_length(v_title) > 120 then
    raise exception '课题标题需要控制在 1 到 120 个字。';
  end if;

  if coalesce(array_length(v_options, 1), 0) <> 4 then
    raise exception '创建投票必须填写 4 个初始选项。';
  end if;

  if exists (
    select 1
    from unnest(v_options) as option_rows(option_label)
    group by lower(btrim(option_label))
    having count(*) > 1
  ) then
    raise exception '初始选项不能重复。';
  end if;

  if exists (
    select 1
    from unnest(v_options) as option_rows(option_label)
    where char_length(btrim(option_label)) > 80
  ) then
    raise exception '每个选项最多 80 个字。';
  end if;

  select count(*)::integer
  into v_daily_count
  from public.polls
  where user_id = v_uid
    and is_deleted = false
    and created_at >= v_day_start
    and created_at < v_day_start + interval '1 day';

  if v_daily_count >= 3 then
    raise exception '每个用户每天最多发起 3 次投票。';
  end if;

  select exists (
    select 1
    from public.profiles
    where id = v_uid
      and role = 'admin'
      and is_banned = false
  ) into v_is_admin;

  if coalesce(p_is_official, false) and not v_is_admin then
    raise exception '只有管理员可以发布官方课题。';
  end if;

  insert into public.polls (user_id, title, is_official, ends_at)
  values (v_uid, v_title, coalesce(p_is_official, false), now() + interval '7 days')
  returning id into v_poll_id;

  insert into public.poll_options (poll_id, user_id, label, source)
  select v_poll_id, null, option_label, 'initial'
  from unnest(v_options) as option_rows(option_label);

  return v_poll_id;
end;
$$;

create or replace function public.fw_add_poll_option(
  p_poll_id bigint,
  p_label text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := public.fw_require_poll_user();
  v_label text := btrim(coalesce(p_label, ''));
  v_poll public.polls%rowtype;
  v_option_count integer := 0;
  v_option_id bigint;
begin
  perform pg_advisory_xact_lock(hashtext('fw_poll_option_' || p_poll_id::text)::bigint);

  select *
  into v_poll
  from public.polls
  where id = p_poll_id
    and is_deleted = false
  for update;

  if not found then
    raise exception '这个课题不存在。';
  end if;

  if v_poll.closed_at is not null or v_poll.ends_at <= now() then
    raise exception '这个课题已经截止，不能新增选项。';
  end if;

  if char_length(v_label) < 1 or char_length(v_label) > 80 then
    raise exception '新增选项需要控制在 1 到 80 个字。';
  end if;

  select count(*)::integer
  into v_option_count
  from public.poll_options
  where poll_id = p_poll_id;

  if v_option_count >= 20 then
    raise exception '每个投票最多 20 个选项。';
  end if;

  if exists (
    select 1
    from public.poll_options
    where poll_id = p_poll_id
      and source = 'user'
      and user_id = v_uid
  ) then
    raise exception '你已经为这个投票新增过 1 个选项。';
  end if;

  if exists (
    select 1
    from public.poll_options
    where poll_id = p_poll_id
      and lower(btrim(label)) = lower(v_label)
  ) then
    raise exception '这个选项已经存在。';
  end if;

  insert into public.poll_options (poll_id, user_id, label, source)
  values (p_poll_id, v_uid, v_label, 'user')
  returning id into v_option_id;

  return v_option_id;
end;
$$;

create or replace function public.fw_vote_poll(
  p_poll_id bigint,
  p_option_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := public.fw_require_poll_user();
  v_poll public.polls%rowtype;
begin
  select *
  into v_poll
  from public.polls
  where id = p_poll_id
    and is_deleted = false;

  if not found then
    raise exception '这个课题不存在。';
  end if;

  if v_poll.closed_at is not null or v_poll.ends_at <= now() then
    raise exception '这个课题已经截止，不能投票或改票。';
  end if;

  if not exists (
    select 1
    from public.poll_options
    where id = p_option_id
      and poll_id = p_poll_id
  ) then
    raise exception '这个选项不属于当前课题。';
  end if;

  insert into public.poll_votes (poll_id, option_id, user_id)
  values (p_poll_id, p_option_id, v_uid)
  on conflict (poll_id, user_id) do update
  set option_id = excluded.option_id,
      updated_at = now();
end;
$$;

create or replace function public.fw_poll_vote_stats()
returns table (
  poll_id bigint,
  option_id bigint,
  vote_count integer,
  poll_participant_count integer
)
language sql
security definer
set search_path = public
as $$
  with visible_options as (
    select
      o.poll_id as poll_id,
      o.id as option_id
    from public.poll_options o
    join public.polls p on p.id = o.poll_id
    where p.is_deleted = false
  ),
  option_counts as (
    select
      v.poll_id as poll_id,
      v.option_id as option_id,
      count(*)::integer as vote_count
    from public.poll_votes v
    join public.polls p on p.id = v.poll_id
    where p.is_deleted = false
    group by v.poll_id, v.option_id
  ),
  participant_counts as (
    select
      v.poll_id as poll_id,
      count(distinct v.user_id)::integer as poll_participant_count
    from public.poll_votes v
    join public.polls p on p.id = v.poll_id
    where p.is_deleted = false
    group by v.poll_id
  )
  select
    vo.poll_id,
    vo.option_id,
    coalesce(oc.vote_count, 0)::integer as vote_count,
    coalesce(pc.poll_participant_count, 0)::integer as poll_participant_count
  from visible_options vo
  left join option_counts oc
    on oc.poll_id = vo.poll_id
   and oc.option_id = vo.option_id
  left join participant_counts pc
    on pc.poll_id = vo.poll_id
  order by vo.poll_id, vo.option_id;
$$;

create or replace function public.fw_my_poll_votes()
returns table (
  poll_id bigint,
  option_id bigint
)
language sql
security definer
set search_path = public
as $$
  select
    v.poll_id,
    v.option_id
  from public.poll_votes v
  join public.polls p on p.id = v.poll_id
  where auth.uid() is not null
    and v.user_id = auth.uid()
    and p.is_deleted = false;
$$;

create or replace function public.fw_delete_my_poll_option(
  p_option_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := public.fw_require_poll_user();
  v_option public.poll_options%rowtype;
  v_poll public.polls%rowtype;
begin
  select *
  into v_option
  from public.poll_options
  where id = p_option_id
  for update;

  if not found then
    raise exception '这个补充选项不存在。';
  end if;

  if v_option.source <> 'user' or v_option.user_id is distinct from v_uid then
    raise exception '只能删除自己补充的选项。';
  end if;

  select *
  into v_poll
  from public.polls
  where id = v_option.poll_id
    and is_deleted = false
  for update;

  if not found then
    raise exception '这个课题不存在。';
  end if;

  if v_poll.closed_at is not null or v_poll.ends_at <= now() then
    raise exception '这个课题已经截止，不能删除选项。';
  end if;

  if exists (
    select 1
    from public.poll_votes
    where poll_id = v_option.poll_id
      and option_id = v_option.id
  ) then
    raise exception '该选项已有投票，不能删除';
  end if;

  delete from public.poll_options
  where id = v_option.id;
end;
$$;

alter table public.polls enable row level security;
alter table public.poll_options enable row level security;
alter table public.poll_votes enable row level security;

drop policy if exists "polls_select_public" on public.polls;
create policy "polls_select_public" on public.polls
for select using (is_deleted = false);

drop policy if exists "poll_options_select_public" on public.poll_options;
create policy "poll_options_select_public" on public.poll_options
for select using (
  exists (
    select 1 from public.polls
    where polls.id = poll_options.poll_id
      and polls.is_deleted = false
  )
);

do $$
declare
  legacy_vote_policy text := 'poll_votes' || '_select_public';
begin
  if exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'poll_votes'
      and policyname = legacy_vote_policy
  ) then
    execute format('drop policy %I on public.poll_votes', legacy_vote_policy);
  end if;
end;
$$;

revoke all on public.polls from anon, authenticated, public;
revoke all on public.poll_options from anon, authenticated, public;
revoke all on public.poll_votes from anon, authenticated, public;

grant select on public.polls to anon, authenticated;
grant select on public.poll_options to anon, authenticated;

grant execute on function public.fw_my_poll_daily_count() to anon, authenticated;
grant execute on function public.fw_create_poll(text, text[], boolean) to authenticated;
grant execute on function public.fw_add_poll_option(bigint, text) to authenticated;
grant execute on function public.fw_vote_poll(bigint, bigint) to authenticated;
grant execute on function public.fw_poll_vote_stats() to anon, authenticated;
revoke execute on function public.fw_my_poll_votes() from anon, public;
grant execute on function public.fw_my_poll_votes() to authenticated;
revoke execute on function public.fw_delete_my_poll_option(bigint) from anon, public;
grant execute on function public.fw_delete_my_poll_option(bigint) to authenticated;