-- F.w 研究所：下班开黑第一版
-- 公开房间信息；游戏 ID 仅本人、队长及已确认成员按需可见。

create table if not exists public.game_parties (
  id bigint generated by default as identity primary key,
  captain_id uuid not null references public.profiles(id) on delete cascade,
  game_name text not null check (char_length(btrim(game_name)) between 1 and 30),
  platform text not null check (platform in ('电脑','手机','主机','跨平台')),
  server_name text not null default '' check (char_length(server_name) <= 30),
  mode text not null default '轻松娱乐' check (mode in ('轻松娱乐','认真上分','新手友好','随缘开麦')),
  starts_at timestamptz not null,
  capacity integer not null check (capacity between 2 and 10),
  member_count integer not null default 0 check (member_count between 0 and 10),
  note text not null default '' check (char_length(note) <= 200),
  status text not null default 'open' check (status in ('open','full','closed','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.game_party_members (
  party_id bigint not null references public.game_parties(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('captain','member')),
  state text not null default 'pending' check (state in ('pending','accepted','rejected','left')),
  request_message text not null default '' check (char_length(request_message) <= 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (party_id,user_id)
);

create table if not exists public.game_party_contacts (
  party_id bigint not null,
  user_id uuid not null,
  game_id text not null check (char_length(btrim(game_id)) between 1 and 60),
  updated_at timestamptz not null default now(),
  primary key (party_id,user_id),
  foreign key (party_id,user_id) references public.game_party_members(party_id,user_id) on delete cascade
);

create table if not exists public.game_party_messages (
  id bigint generated by default as identity primary key,
  party_id bigint not null references public.game_parties(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(btrim(content)) between 1 and 300),
  created_at timestamptz not null default now()
);

create index if not exists game_parties_status_time_idx on public.game_parties(status,starts_at,created_at desc);
create index if not exists game_parties_captain_idx on public.game_parties(captain_id,created_at desc);
create index if not exists game_party_members_user_idx on public.game_party_members(user_id,state,updated_at desc);
create index if not exists game_party_messages_party_idx on public.game_party_messages(party_id,created_at);
create index if not exists game_party_messages_user_idx on public.game_party_messages(user_id);

alter table public.notifications drop constraint if exists notifications_type_check;
alter table public.notifications add constraint notifications_type_check check (type in (
  'like','same','tissue','comment','comment_reply','private_message','friend_request','friend_accept','chat_agree','report','system',
  'game_party_apply','game_party_accepted','game_party_rejected'
)) not valid;

create or replace function public.fw_sync_game_party_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_party_id bigint := coalesce(new.party_id,old.party_id);
  accepted_count integer;
begin
  select count(*)::integer into accepted_count
  from public.game_party_members
  where party_id=target_party_id and state='accepted';

  update public.game_parties
  set member_count=accepted_count,
      status=case
        when status in ('closed','cancelled') then status
        when accepted_count >= capacity then 'full'
        else 'open'
      end,
      updated_at=now()
  where id=target_party_id;
  return coalesce(new,old);
end;
$$;

drop trigger if exists game_party_members_sync_count on public.game_party_members;
create trigger game_party_members_sync_count
after insert or update of state or delete on public.game_party_members
for each row execute function public.fw_sync_game_party_count();

create or replace function public.fw_create_game_party(
  p_game_name text,
  p_platform text,
  p_server_name text,
  p_mode text,
  p_starts_at timestamptz,
  p_capacity integer,
  p_note text,
  p_game_id text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  party_id bigint;
begin
  if me is null or not public.is_not_banned() then raise exception '请先登录。'; end if;
  if char_length(btrim(coalesce(p_game_name,''))) not between 1 and 30 then raise exception '游戏名称需要填写，最多 30 个字。'; end if;
  if coalesce(p_platform,'') not in ('电脑','手机','主机','跨平台') then raise exception '请选择游戏平台。'; end if;
  if coalesce(p_mode,'') not in ('轻松娱乐','认真上分','新手友好','随缘开麦') then raise exception '请选择开黑风格。'; end if;
  if p_starts_at is null or p_starts_at < now()-interval '2 hours' or p_starts_at > now()+interval '30 days' then raise exception '开玩时间需在现在至 30 天内。'; end if;
  if coalesce(p_capacity,0) not between 2 and 10 then raise exception '组队人数需在 2 到 10 人之间。'; end if;
  if char_length(btrim(coalesce(p_game_id,''))) not between 1 and 60 then raise exception '请填写你的游戏 ID，最多 60 个字。'; end if;
  if char_length(coalesce(p_server_name,'')) > 30 or char_length(coalesce(p_note,'')) > 200 then raise exception '房间资料超出字数限制。'; end if;
  if exists(select 1 from public.game_parties where captain_id=me and status in ('open','full') and starts_at>now()-interval '8 hours') then raise exception '你已经有一个仍在进行的组队房间。'; end if;

  insert into public.game_parties(captain_id,game_name,platform,server_name,mode,starts_at,capacity,note)
  values(me,btrim(p_game_name),p_platform,btrim(coalesce(p_server_name,'')),p_mode,p_starts_at,p_capacity,btrim(coalesce(p_note,'')))
  returning id into party_id;
  insert into public.game_party_members(party_id,user_id,role,state) values(party_id,me,'captain','accepted');
  insert into public.game_party_contacts(party_id,user_id,game_id) values(party_id,me,btrim(p_game_id));
  return party_id;
end;
$$;

create or replace function public.fw_apply_game_party(p_party_id bigint,p_game_id text,p_message text default '')
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  party public.game_parties;
  existing_state text;
begin
  if me is null or not public.is_not_banned() then raise exception '请先登录。'; end if;
  if char_length(btrim(coalesce(p_game_id,''))) not between 1 and 60 then raise exception '请填写游戏 ID，最多 60 个字。'; end if;
  if char_length(coalesce(p_message,'')) > 100 then raise exception '申请说明最多 100 个字。'; end if;
  select * into party from public.game_parties where id=p_party_id for update;
  if party.id is null then raise exception '房间不存在。'; end if;
  if party.captain_id=me then return 'captain'; end if;
  if party.status not in ('open','full') then raise exception '这个房间已经结束。'; end if;
  if (select count(*) from public.game_party_members where party_id=p_party_id and state='accepted') >= party.capacity then raise exception '这个房间已经满员。'; end if;
  select state into existing_state from public.game_party_members where party_id=p_party_id and user_id=me;
  if existing_state='accepted' then return 'already_joined'; end if;
  insert into public.game_party_members(party_id,user_id,role,state,request_message)
  values(p_party_id,me,'member','pending',btrim(coalesce(p_message,'')))
  on conflict(party_id,user_id) do update set state='pending',request_message=excluded.request_message,updated_at=now();
  insert into public.game_party_contacts(party_id,user_id,game_id)
  values(p_party_id,me,btrim(p_game_id))
  on conflict(party_id,user_id) do update set game_id=excluded.game_id,updated_at=now();
  insert into public.notifications(user_id,actor_id,type,target_type,target_id,content)
  values(party.captain_id,me,'game_party_apply','game_party',p_party_id,left(btrim(coalesce(p_message,'')),80));
  return 'sent';
end;
$$;

create or replace function public.fw_decide_game_party(p_party_id bigint,p_user_id uuid,p_accept boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  party public.game_parties;
begin
  select * into party from public.game_parties where id=p_party_id for update;
  if me is null or party.id is null or party.captain_id<>me then raise exception '只有队长可以处理申请。'; end if;
  if not exists(select 1 from public.game_party_members where party_id=p_party_id and user_id=p_user_id and state='pending') then raise exception '这条申请已经处理。'; end if;
  if p_accept and (select count(*) from public.game_party_members where party_id=p_party_id and state='accepted') >= party.capacity then raise exception '房间已经满员。'; end if;
  update public.game_party_members set state=case when p_accept then 'accepted' else 'rejected' end,updated_at=now() where party_id=p_party_id and user_id=p_user_id;
  if not p_accept then delete from public.game_party_contacts where party_id=p_party_id and user_id=p_user_id; end if;
  insert into public.notifications(user_id,actor_id,type,target_type,target_id,content)
  values(p_user_id,me,case when p_accept then 'game_party_accepted' else 'game_party_rejected' end,'game_party',p_party_id,case when p_accept then '可以查看队长游戏 ID 并进入队伍聊天' else '这次未能加入，可以看看其他房间' end);
end;
$$;

create or replace function public.fw_leave_game_party(p_party_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
begin
  if exists(select 1 from public.game_parties where id=p_party_id and captain_id=me) then raise exception '队长不能退出，请直接结束房间。'; end if;
  update public.game_party_members set state='left',updated_at=now() where party_id=p_party_id and user_id=me and state in ('pending','accepted');
  delete from public.game_party_contacts where party_id=p_party_id and user_id=me;
end;
$$;

create or replace function public.fw_close_game_party(p_party_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.game_parties set status='closed',updated_at=now() where id=p_party_id and captain_id=auth.uid() and status in ('open','full');
  if not found then raise exception '房间不存在或无权结束。'; end if;
  insert into public.notifications(user_id,actor_id,type,target_type,target_id,content)
  select user_id,auth.uid(),'game_party_rejected','game_party',p_party_id,'队长已结束房间，可以看看其他组队'
  from public.game_party_members where party_id=p_party_id and state='pending';
  delete from public.game_party_contacts c
  using public.game_party_members m
  where c.party_id=m.party_id and c.user_id=m.user_id and m.party_id=p_party_id and m.state='pending';
  update public.game_party_members set state='rejected',updated_at=now() where party_id=p_party_id and state='pending';
end;
$$;

create or replace function public.fw_send_game_party_message(p_party_id bigint,p_content text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  message_id bigint;
begin
  if me is null or not public.can_chat() then raise exception '当前账号无法发送消息。'; end if;
  if char_length(btrim(coalesce(p_content,''))) not between 1 and 300 then raise exception '消息最多 300 个字。'; end if;
  if not exists(select 1 from public.game_party_members where party_id=p_party_id and user_id=me and state='accepted') then raise exception '只有已确认队友可以聊天。'; end if;
  insert into public.game_party_messages(party_id,user_id,content) values(p_party_id,me,btrim(p_content)) returning id into message_id;
  return message_id;
end;
$$;

alter table public.game_parties enable row level security;
alter table public.game_party_members enable row level security;
alter table public.game_party_contacts enable row level security;
alter table public.game_party_messages enable row level security;

drop policy if exists game_parties_select_public on public.game_parties;
create policy game_parties_select_public on public.game_parties for select using (status<>'cancelled');

drop policy if exists game_party_members_select_related on public.game_party_members;
create policy game_party_members_select_related on public.game_party_members for select to authenticated using (
  user_id=(select auth.uid()) or exists(select 1 from public.game_parties p where p.id=party_id and p.captain_id=(select auth.uid()))
);

drop policy if exists game_party_contacts_select_private on public.game_party_contacts;
create policy game_party_contacts_select_private on public.game_party_contacts for select to authenticated using (
  user_id=(select auth.uid())
  or exists(select 1 from public.game_parties p where p.id=party_id and p.captain_id=(select auth.uid()))
  or (
    exists(select 1 from public.game_parties p where p.id=party_id and p.captain_id=game_party_contacts.user_id)
    and exists(select 1 from public.game_party_members m where m.party_id=game_party_contacts.party_id and m.user_id=(select auth.uid()) and m.state='accepted')
  )
);

drop policy if exists game_party_messages_select_members on public.game_party_messages;
create policy game_party_messages_select_members on public.game_party_messages for select to authenticated using (
  exists(select 1 from public.game_party_members m where m.party_id=game_party_messages.party_id and m.user_id=(select auth.uid()) and m.state='accepted')
);

revoke all on public.game_parties,public.game_party_members,public.game_party_contacts,public.game_party_messages from anon,authenticated;
grant select on public.game_parties to anon,authenticated;
grant select on public.game_party_members,public.game_party_contacts,public.game_party_messages to authenticated;

revoke all on function public.fw_create_game_party(text,text,text,text,timestamptz,integer,text,text) from public,anon,authenticated;
revoke all on function public.fw_apply_game_party(bigint,text,text) from public,anon,authenticated;
revoke all on function public.fw_decide_game_party(bigint,uuid,boolean) from public,anon,authenticated;
revoke all on function public.fw_leave_game_party(bigint) from public,anon,authenticated;
revoke all on function public.fw_close_game_party(bigint) from public,anon,authenticated;
revoke all on function public.fw_send_game_party_message(bigint,text) from public,anon,authenticated;
revoke all on function public.fw_sync_game_party_count() from public,anon,authenticated;
grant execute on function public.fw_create_game_party(text,text,text,text,timestamptz,integer,text,text) to authenticated;
grant execute on function public.fw_apply_game_party(bigint,text,text) to authenticated;
grant execute on function public.fw_decide_game_party(bigint,uuid,boolean) to authenticated;
grant execute on function public.fw_leave_game_party(bigint) to authenticated;
grant execute on function public.fw_close_game_party(bigint) to authenticated;
grant execute on function public.fw_send_game_party_message(bigint,text) to authenticated;

do $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='game_parties') then alter publication supabase_realtime add table public.game_parties; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='game_party_members') then alter publication supabase_realtime add table public.game_party_members; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='game_party_messages') then alter publication supabase_realtime add table public.game_party_messages; end if;
end;
$$;
