-- F.w 研究所数据库补丁 05：统一举报闭环
-- 使用方法：在 Supabase SQL Editor 执行。
-- 建议顺序：schema.sql -> auth-base -> social -> rooms -> public-trial -> 本文件。
-- 可重复运行。

-- 1. 统一举报表：承接用户 / 帖子 / 评论举报；房间消息继续兼容既有 chat_message_reports。
create table if not exists public.site_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  target_type text not null check (target_type in ('user','post','comment')),
  target_id text not null,
  target_user_id uuid references public.profiles(id) on delete set null,
  target_display_name text not null default '某位研究员',
  target_preview text,
  report_reason text not null default '用户举报',
  status text not null default 'pending' check (status in ('pending','resolved','ignored')),
  created_at timestamptz not null default now(),
  handled_at timestamptz,
  handled_by uuid references public.profiles(id) on delete set null,
  unique(reporter_id, target_type, target_id)
);

create index if not exists site_reports_status_idx on public.site_reports(status, created_at desc);
create index if not exists site_reports_target_idx on public.site_reports(target_type, target_id);
create index if not exists site_reports_target_user_idx on public.site_reports(target_user_id, created_at desc);

alter table public.site_reports enable row level security;

drop policy if exists "site_reports_insert_self" on public.site_reports;
create policy "site_reports_insert_self" on public.site_reports for insert
  with check (auth.uid() = reporter_id and public.is_not_banned());

drop policy if exists "site_reports_select_admin" on public.site_reports;
create policy "site_reports_select_admin" on public.site_reports for select using (public.is_admin());

drop policy if exists "site_reports_update_admin" on public.site_reports;
create policy "site_reports_update_admin" on public.site_reports for update using (public.is_admin()) with check (public.is_admin());

grant insert, select, update on public.site_reports to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- 2. 前台统一提交举报 RPC。
create or replace function public.fw_submit_report(
  p_target_type text,
  p_target_id text,
  p_reason text default '用户举报'
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  clean_type text := lower(trim(coalesce(p_target_type,'')));
  clean_target text := trim(coalesce(p_target_id,''));
  clean_reason text := left(coalesce(nullif(trim(p_reason),''),'用户举报'), 240);
  owner_id uuid;
  display_name text;
  preview_text text;
  report_id bigint;
begin
  if me is null or not public.is_not_banned() then
    raise exception '请先登录后再举报。';
  end if;

  if clean_type not in ('user','post','comment') then
    raise exception '暂不支持这种举报类型。';
  end if;
  if clean_target = '' then
    raise exception '举报对象不存在。';
  end if;

  if clean_type = 'user' then
    begin
      owner_id := clean_target::uuid;
    exception when others then
      raise exception '被举报用户不存在。';
    end;
    select coalesce(nickname,'某位研究员'), '用户资料 / 搭子关系'
      into display_name, preview_text
      from public.profiles
      where id = owner_id;
  elsif clean_type = 'post' then
    select p.user_id, coalesce(pr.nickname,'某位研究员'), left(coalesce(p.content,''), 220)
      into owner_id, display_name, preview_text
      from public.posts p
      left join public.profiles pr on pr.id = p.user_id
      where p.id::text = clean_target;
  elsif clean_type = 'comment' then
    select c.user_id, coalesce(pr.nickname,'某位研究员'), left(coalesce(c.content,''), 220)
      into owner_id, display_name, preview_text
      from public.comments c
      left join public.profiles pr on pr.id = c.user_id
      where c.id::text = clean_target;
  end if;

  if owner_id is null then
    raise exception '举报对象不存在或已被处理。';
  end if;
  if owner_id = me then
    raise exception '不能举报自己发布的内容。';
  end if;

  insert into public.site_reports(reporter_id,target_type,target_id,target_user_id,target_display_name,target_preview,report_reason,status,created_at,handled_at,handled_by)
  values(me, clean_type, clean_target, owner_id, coalesce(display_name,'某位研究员'), preview_text, clean_reason, 'pending', now(), null, null)
  on conflict(reporter_id,target_type,target_id) do update set
    report_reason = excluded.report_reason,
    status = 'pending',
    created_at = now(),
    handled_at = null,
    handled_by = null
  returning id into report_id;

  return report_id;
end;
$$;

-- 兼容旧电脑端搭子举报入口：保持旧返回类型 void，避免旧库报 42P13。
create or replace function public.fw_report_user(target_user_id uuid, report_reason text default '用户举报')
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.fw_submit_report('user', target_user_id::text, report_reason);
end;
$$;

-- 3. 后台统一读取举报：继续沿用前端现有 admin_list_chat_reports 名称，避免改后台主流程。
--    chat_message_reports 保持原样；site_reports 用负数 id 映射，admin_resolve_chat_report 可识别。
create or replace function public.admin_list_chat_reports()
returns table(
  id bigint,
  message_id bigint,
  reporter_id uuid,
  reporter_name text,
  target_user_id uuid,
  target_name text,
  room_key text,
  message_content text,
  report_reason text,
  status text,
  created_at timestamptz,
  handled_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select r.id, r.message_id, r.reporter_id, rp.nickname as reporter_name,
         m.user_id as target_user_id, tp.nickname as target_name, m.room_key,
         m.content as message_content, coalesce(r.report_reason, '用户举报') as report_reason, coalesce(r.status,'pending') as status,
         r.created_at, r.handled_at
  from public.chat_message_reports r
  left join public.chat_messages m on m.id = r.message_id
  left join public.profiles rp on rp.id = r.reporter_id
  left join public.profiles tp on tp.id = m.user_id
  where public.is_admin()

  union all

  select -sr.id as id, null::bigint as message_id, sr.reporter_id, rp.nickname as reporter_name,
         sr.target_user_id, sr.target_display_name as target_name, sr.target_type as room_key,
         sr.target_preview as message_content, sr.report_reason, sr.status, sr.created_at, sr.handled_at
  from public.site_reports sr
  left join public.profiles rp on rp.id = sr.reporter_id
  where public.is_admin()

  order by created_at desc
  limit 240;
$$;

-- 4. 后台处理举报：兼容旧 chat_message_reports，也处理新的 site_reports。
create or replace function public.admin_resolve_chat_report(
  p_report_id bigint,
  p_status text default 'resolved',
  p_reason text default '举报已处理',
  p_public_visible boolean default false
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  msg_id bigint;
  owner_id uuid;
  site_id bigint;
begin
  if not public.is_admin() then raise exception 'Only admin can resolve reports'; end if;
  if p_status not in ('resolved','ignored') then raise exception '举报状态只能是 resolved 或 ignored'; end if;

  if p_report_id < 0 then
    site_id := abs(p_report_id);
    select target_user_id into owner_id from public.site_reports where id = site_id;
    if owner_id is null then raise exception '举报不存在'; end if;
    update public.site_reports
      set status = p_status, handled_at = now(), handled_by = auth.uid()
      where id = site_id;
    perform public.fw_log_moderation('report', site_id::text, owner_id,
      case when p_status = 'resolved' then 'resolve_report' else 'ignore_report' end,
      p_reason, null, p_public_visible, null);
    return;
  end if;

  select message_id into msg_id from public.chat_message_reports where id = p_report_id;
  if msg_id is null then raise exception '举报不存在'; end if;
  update public.chat_message_reports set status = p_status, handled_at = now(), handled_by = auth.uid() where id = p_report_id;
  select user_id into owner_id from public.chat_messages where id = msg_id;
  perform public.fw_log_moderation('report',p_report_id::text,owner_id,case when p_status = 'resolved' then 'resolve_report' else 'ignore_report' end,p_reason,null,p_public_visible,null);
end;
$$;

grant execute on function public.fw_submit_report(text,text,text) to authenticated;
grant execute on function public.fw_report_user(uuid,text) to authenticated;
grant execute on function public.admin_list_chat_reports() to authenticated;
grant execute on function public.admin_resolve_chat_report(bigint,text,text,boolean) to authenticated;
