-- F.w 研究所数据库补丁 03：摸鱼房间聊天
-- 使用方法：先运行 patch-20260510-auth-base.sql，再运行本文件。
-- 可重复运行。

-- 1. 表结构
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  room_key text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 300),
  reply_to_id bigint references public.chat_messages(id) on delete set null,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists chat_messages_room_idx on public.chat_messages(room_key, created_at desc);

create table if not exists public.chat_message_reactions (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.chat_messages(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null default 'agree' check (type in ('agree')),
  created_at timestamptz not null default now(),
  unique(message_id, user_id, type)
);

create table if not exists public.chat_message_reports (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.chat_messages(id) on delete cascade,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  report_reason text,
  created_at timestamptz not null default now(),
  unique(message_id, reporter_id)
);

-- 2. 管理 RPC
create or replace function public.admin_set_user_banned(target_user_id uuid, banned boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Only admin can update user status'; end if;
  update public.profiles
  set is_banned = banned, updated_at = now()
  where id = target_user_id and role <> 'admin';
end;
$$;

create or replace function public.admin_set_user_muted(target_user_id uuid, mute_minutes int)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Only admin can mute users'; end if;
  update public.profiles
  set muted_until = now() + make_interval(mins => greatest(coalesce(mute_minutes,0),0)), updated_at = now()
  where id = target_user_id and role <> 'admin';
end;
$$;

-- 3. 房间 RPC：赞同 / 举报 / 撤回 / 管理删除
create or replace function public.agree_chat_message(target_message_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  owner_id uuid;
begin
  if me is null or not public.is_not_banned() then raise exception '请先登录。'; end if;

  select user_id into owner_id from public.chat_messages where id = target_message_id and is_deleted = false;
  if owner_id is null then raise exception '消息不存在。'; end if;

  insert into public.chat_message_reactions(message_id, user_id, type)
  values(target_message_id, me, 'agree')
  on conflict(message_id, user_id, type) do nothing;

  if owner_id <> me and to_regclass('public.notifications') is not null then
    insert into public.notifications(user_id, actor_id, type, target_type, target_id, content)
    values(owner_id, me, 'chat_agree', 'chat_message', target_message_id, '赞同了你的房间消息');
  end if;
end;
$$;

create or replace function public.report_chat_message(target_message_id bigint, report_reason text default '用户举报')
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception '请先登录。'; end if;
  insert into public.chat_message_reports(message_id, reporter_id, report_reason)
  values(target_message_id, auth.uid(), left(coalesce(report_reason,'用户举报'), 200))
  on conflict(message_id, reporter_id) do update set report_reason = excluded.report_reason, created_at = now();
end;
$$;

create or replace function public.recall_own_chat_message(target_message_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.chat_messages
  set is_deleted = true
  where id = target_message_id
    and user_id = auth.uid()
    and created_at >= now() - interval '2 minutes';
end;
$$;

create or replace function public.admin_delete_chat_message(target_message_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Only admin can delete chat messages'; end if;
  update public.chat_messages set is_deleted = true where id = target_message_id;
end;
$$;

-- 4. RLS
alter table public.chat_messages enable row level security;
alter table public.chat_message_reactions enable row level security;
alter table public.chat_message_reports enable row level security;

drop policy if exists "chat_messages_select_public" on public.chat_messages;
create policy "chat_messages_select_public" on public.chat_messages for select using (is_deleted = false);

drop policy if exists "chat_messages_insert_user" on public.chat_messages;
create policy "chat_messages_insert_user" on public.chat_messages for insert with check (auth.uid() = user_id and public.can_chat());

drop policy if exists "chat_messages_update_admin_or_own" on public.chat_messages;
create policy "chat_messages_update_admin_or_own" on public.chat_messages for update using (public.is_admin() or auth.uid() = user_id) with check (public.is_admin() or auth.uid() = user_id);

drop policy if exists "chat_reactions_select_public" on public.chat_message_reactions;
create policy "chat_reactions_select_public" on public.chat_message_reactions for select using (true);

drop policy if exists "chat_reports_insert_user" on public.chat_message_reports;
create policy "chat_reports_insert_user" on public.chat_message_reports for insert with check (auth.uid() = reporter_id and public.is_not_banned());

-- 5. 授权
grant select, insert, update on public.chat_messages to authenticated;
grant select on public.chat_messages to anon;
grant select, insert on public.chat_message_reactions to authenticated;
grant insert on public.chat_message_reports to authenticated;
grant usage, select on all sequences in schema public to authenticated;

grant execute on function public.admin_set_user_banned(uuid, boolean) to authenticated;
grant execute on function public.admin_set_user_muted(uuid, int) to authenticated;
grant execute on function public.agree_chat_message(bigint) to authenticated;
grant execute on function public.report_chat_message(bigint, text) to authenticated;
grant execute on function public.recall_own_chat_message(bigint) to authenticated;
grant execute on function public.admin_delete_chat_message(bigint) to authenticated;
