-- F.w 研究所数据库补丁 02：回声 / 搭子 / 私聊
-- 使用方法：先运行 patch-20260510-auth-base.sql，再运行本文件。
-- 可重复运行。
-- 修复说明：如果旧库里已经存在同名 RPC 且返回值不同，先 DROP 再重建，避免 42P13 报错。

-- 1. 表结构
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  type text not null,
  target_type text,
  target_id bigint,
  content text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists notifications_user_unread_idx on public.notifications(user_id, is_read, created_at desc);

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','rejected','blocked')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (requester_id <> receiver_id)
);
create unique index if not exists friendships_pair_unique_idx
  on public.friendships (least(requester_id, receiver_id), greatest(requester_id, receiver_id));
create index if not exists friendships_requester_idx on public.friendships(requester_id, status);
create index if not exists friendships_receiver_idx on public.friendships(receiver_id, status);

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  user_one_id uuid not null references public.profiles(id) on delete cascade,
  user_two_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (user_one_id <> user_two_id)
);
create unique index if not exists conversations_pair_unique_idx
  on public.conversations (least(user_one_id, user_two_id), greatest(user_one_id, user_two_id));

create table if not exists public.private_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 300),
  is_deleted boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists private_messages_conversation_idx on public.private_messages(conversation_id, created_at);

-- 2. RPC：搭子申请
create or replace function public.fw_send_friend_request(target_user_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  f public.friendships;
begin
  if me is null or not public.is_not_banned() then raise exception '请先登录。'; end if;
  if target_user_id = me then return 'self'; end if;

  select * into f from public.friendships
  where (requester_id = me and receiver_id = target_user_id)
     or (requester_id = target_user_id and receiver_id = me)
  limit 1;

  if f.id is not null then
    if f.status = 'accepted' then return 'already_accepted'; end if;
    if f.status = 'pending' then return 'already_pending'; end if;
    if f.status = 'blocked' then return 'blocked'; end if;
    update public.friendships
      set requester_id = me, receiver_id = target_user_id, status = 'pending', updated_at = now()
      where id = f.id returning * into f;
  else
    insert into public.friendships(requester_id, receiver_id, status)
    values(me, target_user_id, 'pending') returning * into f;
  end if;

  insert into public.notifications(user_id, actor_id, type, target_type, target_id, content)
  values(target_user_id, me, 'friend_request', 'friendship', f.id, '想加你为搭子');

  return 'sent';
end;
$$;

drop function if exists public.fw_respond_friendship(bigint, boolean);
create function public.fw_respond_friendship(target_friendship_id bigint, accept_request boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  f public.friendships;
begin
  select * into f from public.friendships where id = target_friendship_id and receiver_id = me and status = 'pending';
  if f.id is null then raise exception '申请不存在或无权处理。'; end if;

  update public.friendships
  set status = case when accept_request then 'accepted' else 'rejected' end,
      updated_at = now()
  where id = f.id;

  if accept_request then
    insert into public.notifications(user_id, actor_id, type, target_type, target_id, content)
    values(f.requester_id, me, 'friend_accept', 'friendship', f.id, '通过了你的搭子申请');
  end if;
end;
$$;

create or replace function public.fw_remove_friendship(target_friendship_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.friendships
  where id = target_friendship_id
    and (requester_id = auth.uid() or receiver_id = auth.uid());
end;
$$;

create or replace function public.fw_block_user(target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  f_id bigint;
begin
  if me is null or target_user_id = me then return; end if;

  select id into f_id from public.friendships
  where (requester_id = me and receiver_id = target_user_id)
     or (requester_id = target_user_id and receiver_id = me)
  limit 1;

  if f_id is null then
    insert into public.friendships(requester_id, receiver_id, status)
    values(me, target_user_id, 'blocked');
  else
    update public.friendships
    set requester_id = me, receiver_id = target_user_id, status = 'blocked', updated_at = now()
    where id = f_id;
  end if;
end;
$$;

-- 3. RPC：私聊
create or replace function public.fw_get_or_create_conversation(target_user_id uuid)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  conv_id bigint;
begin
  if me is null or target_user_id = me then raise exception '无法创建私聊。'; end if;

  if not exists(
    select 1 from public.friendships
    where status = 'accepted'
      and ((requester_id = me and receiver_id = target_user_id) or (requester_id = target_user_id and receiver_id = me))
  ) then
    raise exception '只有成为搭子后才能私聊。';
  end if;

  select id into conv_id from public.conversations
  where (user_one_id = me and user_two_id = target_user_id)
     or (user_one_id = target_user_id and user_two_id = me)
  limit 1;

  if conv_id is null then
    insert into public.conversations(user_one_id, user_two_id)
    values(me, target_user_id) returning id into conv_id;
  end if;

  return conv_id;
end;
$$;

create or replace function public.fw_send_private_message(target_conversation_id bigint, message_text text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  c public.conversations;
  receiver uuid;
  msg_id bigint;
begin
  if me is null or not public.can_chat() then raise exception '当前账号无法发送消息。'; end if;
  if char_length(trim(coalesce(message_text,''))) < 1 or char_length(trim(message_text)) > 300 then raise exception '私聊最多 300 字。'; end if;

  select * into c from public.conversations
  where id = target_conversation_id and (user_one_id = me or user_two_id = me);
  if c.id is null then raise exception '无权发送该私聊。'; end if;

  receiver := case when c.user_one_id = me then c.user_two_id else c.user_one_id end;

  insert into public.private_messages(conversation_id, sender_id, content)
  values(target_conversation_id, me, trim(message_text)) returning id into msg_id;

  update public.conversations set updated_at = now() where id = target_conversation_id;

  insert into public.notifications(user_id, actor_id, type, target_type, target_id, content)
  values(receiver, me, 'private_message', 'private_message', msg_id, left(trim(message_text), 80));
end;
$$;

-- 4. RLS
alter table public.notifications enable row level security;
alter table public.friendships enable row level security;
alter table public.conversations enable row level security;
alter table public.private_messages enable row level security;

drop policy if exists "notifications_select_own" on public.notifications;
create policy "notifications_select_own" on public.notifications for select using (auth.uid() = user_id);

drop policy if exists "notifications_update_own" on public.notifications;
create policy "notifications_update_own" on public.notifications for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "friendships_select_own" on public.friendships;
create policy "friendships_select_own" on public.friendships for select using (auth.uid() = requester_id or auth.uid() = receiver_id);

drop policy if exists "conversations_select_own" on public.conversations;
create policy "conversations_select_own" on public.conversations for select using (auth.uid() = user_one_id or auth.uid() = user_two_id);

drop policy if exists "private_messages_select_own" on public.private_messages;
create policy "private_messages_select_own" on public.private_messages for select using (
  exists(select 1 from public.conversations c where c.id = conversation_id and (c.user_one_id = auth.uid() or c.user_two_id = auth.uid()))
);

-- 5. 授权
grant select, update on public.notifications to authenticated;
grant select on public.friendships to authenticated;
grant select on public.conversations to authenticated;
grant select on public.private_messages to authenticated;
grant usage, select on all sequences in schema public to authenticated;

grant execute on function public.fw_send_friend_request(uuid) to authenticated;
grant execute on function public.fw_respond_friendship(bigint, boolean) to authenticated;
grant execute on function public.fw_remove_friendship(bigint) to authenticated;
grant execute on function public.fw_block_user(uuid) to authenticated;
grant execute on function public.fw_get_or_create_conversation(uuid) to authenticated;
grant execute on function public.fw_send_private_message(bigint, text) to authenticated;
