-- F.w 研究所数据库补丁 04：公开处刑 / 管理后台
-- 使用方法：Supabase SQL Editor 执行。建议顺序：schema.sql -> auth-base -> social -> rooms -> 本文件。
-- 可重复运行。

-- 1. 公开处刑记录
create table if not exists public.moderation_logs (
  id bigint generated by default as identity primary key,
  target_type text not null default 'user',
  target_id text,
  target_user_id uuid references public.profiles(id) on delete set null,
  target_display_name text not null default '某位研究员',
  action text not null default 'system_note',
  reason text not null default '违反研究所公约',
  duration_text text,
  public_visible boolean not null default true,
  is_revoked boolean not null default false,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz
);

create index if not exists moderation_logs_public_idx on public.moderation_logs(public_visible, is_revoked, created_at desc);
create index if not exists moderation_logs_user_idx on public.moderation_logs(target_user_id, created_at desc);
alter table public.moderation_logs enable row level security;

drop policy if exists "moderation_logs_public_read" on public.moderation_logs;
create policy "moderation_logs_public_read" on public.moderation_logs for select using (public_visible = true and is_revoked = false);

drop policy if exists "moderation_logs_admin_read" on public.moderation_logs;
create policy "moderation_logs_admin_read" on public.moderation_logs for select using (public.is_admin());

drop policy if exists "moderation_logs_admin_insert" on public.moderation_logs;
create policy "moderation_logs_admin_insert" on public.moderation_logs for insert with check (public.is_admin());

drop policy if exists "moderation_logs_admin_update" on public.moderation_logs;
create policy "moderation_logs_admin_update" on public.moderation_logs for update using (public.is_admin()) with check (public.is_admin());

grant select on public.moderation_logs to anon, authenticated;
grant insert, update on public.moderation_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- 2. 管理员可读取软删除内容，普通用户仍只看未删除内容
drop policy if exists "posts_select_public" on public.posts;
create policy "posts_select_public" on public.posts for select using (is_deleted = false or public.is_admin());

drop policy if exists "comments_select_public" on public.comments;
create policy "comments_select_public" on public.comments for select using (is_deleted = false or public.is_admin());

do $$ begin
  if to_regclass('public.chat_messages') is not null then
    execute 'drop policy if exists "chat_messages_select_public" on public.chat_messages';
    execute 'create policy "chat_messages_select_public" on public.chat_messages for select using (is_deleted = false or public.is_admin())';
  end if;
end $$;

-- 3. 举报处理字段
do $$ begin
  if to_regclass('public.chat_message_reports') is not null then
    alter table public.chat_message_reports add column if not exists status text not null default 'pending';
    alter table public.chat_message_reports add column if not exists handled_at timestamptz;
    alter table public.chat_message_reports add column if not exists handled_by uuid references public.profiles(id) on delete set null;

    execute 'drop policy if exists "chat_reports_select_admin" on public.chat_message_reports';
    execute 'create policy "chat_reports_select_admin" on public.chat_message_reports for select using (public.is_admin())';
    execute 'drop policy if exists "chat_reports_update_admin" on public.chat_message_reports';
    execute 'create policy "chat_reports_update_admin" on public.chat_message_reports for update using (public.is_admin()) with check (public.is_admin())';
    grant select, update on public.chat_message_reports to authenticated;
  end if;
end $$;

-- 4. 当前用户安全资料：前端不再直接读取 profiles.role / is_banned 等敏感列
create or replace function public.fw_get_current_profile()
returns table(
  id uuid,
  email text,
  nickname text,
  avatar_url text,
  role text,
  is_banned boolean,
  lab_code text,
  muted_until timestamptz,
  created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select p.id, u.email, p.nickname, p.avatar_url, p.role, p.is_banned, p.lab_code, p.muted_until, p.created_at
  from public.profiles p
  left join auth.users u on u.id = p.id
  where p.id = auth.uid();
$$;

-- 5. 管理员列表 RPC
create or replace function public.admin_list_profiles()
returns table(
  id uuid,
  nickname text,
  avatar_url text,
  role text,
  is_banned boolean,
  lab_code text,
  muted_until timestamptz,
  created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select p.id, p.nickname, p.avatar_url, p.role, p.is_banned, p.lab_code, p.muted_until, p.created_at
  from public.profiles p
  where public.is_admin()
  order by p.created_at desc
  limit 300;
$$;

create or replace function public.admin_list_chat_reports()
returns table(
  id bigint,
  message_id bigint,
  reporter_id uuid,
  reporter_name text,
  target_user_id uuid,
  target_name text,
  room_key text,
  message_content text,
  report_reason text,
  status text,
  created_at timestamptz,
  handled_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select r.id, r.message_id, r.reporter_id, rp.nickname as reporter_name,
         m.user_id as target_user_id, tp.nickname as target_name, m.room_key,
         m.content as message_content, r.report_reason, coalesce(r.status,'pending') as status,
         r.created_at, r.handled_at
  from public.chat_message_reports r
  left join public.chat_messages m on m.id = r.message_id
  left join public.profiles rp on rp.id = r.reporter_id
  left join public.profiles tp on tp.id = m.user_id
  where public.is_admin()
  order by r.created_at desc
  limit 200;
$$;

create or replace function public.admin_list_chat_messages()
returns table(
  id bigint,
  room_key text,
  user_id uuid,
  nickname text,
  avatar_url text,
  content text,
  is_deleted boolean,
  created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select m.id, m.room_key, m.user_id, p.nickname, p.avatar_url, m.content, m.is_deleted, m.created_at
  from public.chat_messages m
  left join public.profiles p on p.id = m.user_id
  where public.is_admin()
  order by m.created_at desc
  limit 200;
$$;

-- 6. 公开处刑记录写入
create or replace function public.fw_public_name(p_user_id uuid)
returns text language sql security definer set search_path = public as $$
  select coalesce((select nickname from public.profiles where id = p_user_id), '某位研究员');
$$;

create or replace function public.fw_log_moderation(
  p_target_type text,
  p_target_id text,
  p_target_user_id uuid,
  p_action text,
  p_reason text default '违反研究所公约',
  p_duration_text text default null,
  p_public_visible boolean default true,
  p_expires_at timestamptz default null
)
returns bigint language plpgsql security definer set search_path = public as $$
declare new_id bigint;
begin
  if not public.is_admin() then raise exception 'Only admin can write moderation logs'; end if;
  insert into public.moderation_logs(target_type,target_id,target_user_id,target_display_name,action,reason,duration_text,public_visible,created_by,expires_at)
  values (p_target_type,p_target_id,p_target_user_id,public.fw_public_name(p_target_user_id),p_action,coalesce(nullif(trim(p_reason),''),'违反研究所公约'),p_duration_text,coalesce(p_public_visible,true),auth.uid(),p_expires_at)
  returning id into new_id;
  return new_id;
end;
$$;

-- 7. 管理操作 RPC
create or replace function public.admin_moderate_user(p_target_user_id uuid,p_action text,p_mute_minutes int default null,p_reason text default '违反研究所公约',p_public_visible boolean default true)
returns void language plpgsql security definer set search_path = public as $$
declare target_role text; until_time timestamptz; duration_label text;
begin
  if not public.is_admin() then raise exception 'Only admin can moderate users'; end if;
  select role into target_role from public.profiles where id = p_target_user_id;
  if target_role is null then raise exception '用户不存在'; end if;
  if target_role = 'admin' then raise exception '不能处理管理员账号'; end if;
  if p_action = 'ban' then
    update public.profiles set is_banned = true, updated_at = now() where id = p_target_user_id;
    perform public.fw_log_moderation('user',p_target_user_id::text,p_target_user_id,'ban',p_reason,null,p_public_visible,null);
  elsif p_action = 'unban' then
    update public.profiles set is_banned = false, updated_at = now() where id = p_target_user_id;
    perform public.fw_log_moderation('user',p_target_user_id::text,p_target_user_id,'unban',p_reason,null,p_public_visible,null);
  elsif p_action = 'mute' then
    until_time := now() + make_interval(mins => greatest(coalesce(p_mute_minutes,1440),1));
    duration_label := case when coalesce(p_mute_minutes,1440) >= 1440 then (coalesce(p_mute_minutes,1440)/1440)::text || ' 天' when coalesce(p_mute_minutes,1440) >= 60 then (coalesce(p_mute_minutes,1440)/60)::text || ' 小时' else coalesce(p_mute_minutes,1440)::text || ' 分钟' end;
    update public.profiles set muted_until = until_time, updated_at = now() where id = p_target_user_id;
    perform public.fw_log_moderation('user',p_target_user_id::text,p_target_user_id,'mute',p_reason,duration_label,p_public_visible,until_time);
  elsif p_action = 'unmute' then
    update public.profiles set muted_until = null, updated_at = now() where id = p_target_user_id;
    perform public.fw_log_moderation('user',p_target_user_id::text,p_target_user_id,'unmute',p_reason,null,p_public_visible,null);
  else raise exception '未知处理动作'; end if;
end;
$$;

create or replace function public.admin_moderate_post(p_post_id bigint,p_delete boolean default true,p_reason text default '内容不适合公开展示',p_public_visible boolean default true)
returns void language plpgsql security definer set search_path = public as $$
declare owner_id uuid;
begin
  if not public.is_admin() then raise exception 'Only admin can moderate posts'; end if;
  select user_id into owner_id from public.posts where id = p_post_id;
  if owner_id is null then raise exception '帖子不存在'; end if;
  update public.posts set is_deleted = p_delete where id = p_post_id;
  perform public.fw_log_moderation('post',p_post_id::text,owner_id,case when p_delete then 'delete_post' else 'restore_post' end,p_reason,null,p_public_visible,null);
end;
$$;

create or replace function public.admin_moderate_comment(p_comment_id bigint,p_delete boolean default true,p_reason text default '评论不适合公开展示',p_public_visible boolean default true)
returns void language plpgsql security definer set search_path = public as $$
declare owner_id uuid;
begin
  if not public.is_admin() then raise exception 'Only admin can moderate comments'; end if;
  select user_id into owner_id from public.comments where id = p_comment_id;
  if owner_id is null then raise exception '评论不存在'; end if;
  update public.comments set is_deleted = p_delete where id = p_comment_id;
  perform public.fw_log_moderation('comment',p_comment_id::text,owner_id,case when p_delete then 'delete_comment' else 'restore_comment' end,p_reason,null,p_public_visible,null);
end;
$$;

create or replace function public.admin_moderate_chat_message(p_message_id bigint,p_delete boolean default true,p_reason text default '房间消息不适合公开展示',p_public_visible boolean default true)
returns void language plpgsql security definer set search_path = public as $$
declare owner_id uuid;
begin
  if not public.is_admin() then raise exception 'Only admin can moderate chat messages'; end if;
  select user_id into owner_id from public.chat_messages where id = p_message_id;
  if owner_id is null then raise exception '消息不存在'; end if;
  update public.chat_messages set is_deleted = p_delete where id = p_message_id;
  perform public.fw_log_moderation('chat_message',p_message_id::text,owner_id,case when p_delete then 'delete_chat_message' else 'restore_chat_message' end,p_reason,null,p_public_visible,null);
end;
$$;

create or replace function public.admin_resolve_chat_report(p_report_id bigint,p_status text default 'resolved',p_reason text default '举报已处理',p_public_visible boolean default false)
returns void language plpgsql security definer set search_path = public as $$
declare msg_id bigint; owner_id uuid;
begin
  if not public.is_admin() then raise exception 'Only admin can resolve reports'; end if;
  if p_status not in ('resolved','ignored') then raise exception '举报状态只能是 resolved 或 ignored'; end if;
  select message_id into msg_id from public.chat_message_reports where id = p_report_id;
  if msg_id is null then raise exception '举报不存在'; end if;
  update public.chat_message_reports set status = p_status, handled_at = now(), handled_by = auth.uid() where id = p_report_id;
  select user_id into owner_id from public.chat_messages where id = msg_id;
  perform public.fw_log_moderation('report',p_report_id::text,owner_id,case when p_status = 'resolved' then 'resolve_report' else 'ignore_report' end,p_reason,null,p_public_visible,null);
end;
$$;

-- 8. profiles 权限收紧：公开只读展示字段；敏感字段走 RPC
revoke select on public.profiles from anon, authenticated;
grant select (id, nickname, avatar_url, lab_code, created_at) on public.profiles to anon, authenticated;
grant update (nickname, avatar_url, lab_code, email_search, nickname_change_year, nickname_change_count, updated_at) on public.profiles to authenticated;

grant execute on function public.fw_get_current_profile() to authenticated;
grant execute on function public.admin_list_profiles() to authenticated;
grant execute on function public.admin_list_chat_reports() to authenticated;
grant execute on function public.admin_list_chat_messages() to authenticated;
grant execute on function public.fw_public_name(uuid) to anon, authenticated;
grant execute on function public.fw_log_moderation(text,text,uuid,text,text,text,boolean,timestamptz) to authenticated;
grant execute on function public.admin_moderate_user(uuid,text,int,text,boolean) to authenticated;
grant execute on function public.admin_moderate_post(bigint,boolean,text,boolean) to authenticated;
grant execute on function public.admin_moderate_comment(bigint,boolean,text,boolean) to authenticated;
grant execute on function public.admin_moderate_chat_message(bigint,boolean,text,boolean) to authenticated;
grant execute on function public.admin_resolve_chat_report(bigint,text,text,boolean) to authenticated;
