-- F.w 研究所：轻量会员基础。
-- 第一阶段只建立套餐、会员状态、订单与支付回调占位；真实订单只能由后续服务端支付函数写入。

begin;

create table if not exists public.membership_plans (
  id text primary key,
  name text not null,
  duration_months integer not null,
  price_cents integer not null,
  compare_at_price_cents integer,
  is_recommended boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint membership_plans_id_check check (id ~ '^[a-z0-9_]+$'),
  constraint membership_plans_duration_check check (duration_months between 1 and 24),
  constraint membership_plans_price_check check (price_cents >= 0),
  constraint membership_plans_compare_price_check check (compare_at_price_cents is null or compare_at_price_cents >= price_cents)
);

create table if not exists public.memberships (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  plan_id text references public.membership_plans(id) on delete set null,
  status text not null default 'active',
  starts_at timestamptz not null default now(),
  expires_at timestamptz not null,
  source text not null default 'payment',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint memberships_status_check check (status in ('active','expired','cancelled')),
  constraint memberships_source_check check (source in ('payment','manual','gift','migration')),
  constraint memberships_time_check check (expires_at > starts_at)
);

create index if not exists memberships_active_user_idx
  on public.memberships(user_id, expires_at desc)
  where status='active';

create table if not exists public.membership_orders (
  id uuid primary key default gen_random_uuid(),
  order_no text not null unique,
  user_id uuid not null references public.profiles(id) on delete cascade,
  plan_id text not null references public.membership_plans(id),
  amount_cents integer not null,
  payment_method text,
  status text not null default 'pending',
  provider_order_id text,
  provider_transaction_id text,
  payment_qr_url text,
  payment_expires_at timestamptz,
  paid_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint membership_orders_amount_check check (amount_cents >= 0),
  constraint membership_orders_method_check check (payment_method is null or payment_method in ('wechat','alipay')),
  constraint membership_orders_status_check check (status in ('pending','paid','closed','refunded','failed'))
);

create index if not exists membership_orders_user_created_idx
  on public.membership_orders(user_id, created_at desc);

create index if not exists membership_orders_pending_idx
  on public.membership_orders(status, payment_expires_at)
  where status='pending';

create table if not exists public.membership_payment_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  provider_event_id text not null,
  order_id uuid references public.membership_orders(id) on delete set null,
  process_status text not null default 'received',
  payload jsonb not null default '{}'::jsonb,
  error_message text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  constraint membership_payment_events_provider_check check (provider in ('wechat','alipay')),
  constraint membership_payment_events_status_check check (process_status in ('received','processed','ignored','failed')),
  constraint membership_payment_events_provider_id_unique unique(provider,provider_event_id)
);

insert into public.membership_plans(id,name,duration_months,price_cents,compare_at_price_cents,is_recommended,is_active,sort_order)
values
  ('monthly','月度会员',1,200,990,false,true,1),
  ('quarterly','季度会员',3,2500,2970,false,true,2),
  ('yearly','年度会员',12,8800,11880,true,true,3)
on conflict(id) do update set
  name=excluded.name,
  duration_months=excluded.duration_months,
  price_cents=excluded.price_cents,
  compare_at_price_cents=excluded.compare_at_price_cents,
  is_recommended=excluded.is_recommended,
  is_active=excluded.is_active,
  sort_order=excluded.sort_order,
  updated_at=now();

alter table public.membership_plans enable row level security;
alter table public.memberships enable row level security;
alter table public.membership_orders enable row level security;
alter table public.membership_payment_events enable row level security;

drop policy if exists "membership_plans_read_active" on public.membership_plans;
create policy "membership_plans_read_active"
  on public.membership_plans for select
  to anon,authenticated
  using (is_active or public.is_admin());

drop policy if exists "memberships_read_own" on public.memberships;
create policy "memberships_read_own"
  on public.memberships for select
  to authenticated
  using ((select auth.uid())=user_id or public.is_admin());

drop policy if exists "membership_orders_read_own" on public.membership_orders;
create policy "membership_orders_read_own"
  on public.membership_orders for select
  to authenticated
  using ((select auth.uid())=user_id or public.is_admin());

revoke all on table public.membership_plans from public,anon,authenticated;
revoke all on table public.memberships from public,anon,authenticated;
revoke all on table public.membership_orders from public,anon,authenticated;
revoke all on table public.membership_payment_events from public,anon,authenticated;
grant select on table public.membership_plans to anon,authenticated;
grant select on table public.memberships to authenticated;
grant select on table public.membership_orders to authenticated;
grant all on table public.membership_plans to service_role;
grant all on table public.memberships to service_role;
grant all on table public.membership_orders to service_role;
grant all on table public.membership_payment_events to service_role;
grant usage,select on sequence public.membership_payment_events_id_seq to service_role;

-- 只公开“当前是否为会员”这一项，供头像资料卡展示标识；不公开到期时间和订单信息。
create or replace function public.fw_has_active_membership(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1
    from public.memberships m
    where m.user_id=p_user_id
      and m.status='active'
      and m.starts_at<=now()
      and m.expires_at>now()
  );
$$;

revoke all on function public.fw_has_active_membership(uuid) from public,anon,authenticated;
grant execute on function public.fw_has_active_membership(uuid) to anon,authenticated;

-- 会员最多创建 15 个活动组队，普通研究员继续保持 5 个。
create or replace function public.fw_create_game_party(
  p_game_name text,
  p_platform text,
  p_server_name text,
  p_mode text,
  p_starts_at timestamptz,
  p_capacity integer,
  p_note text,
  p_game_id text,
  p_requires_approval boolean,
  p_starts_at_text text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  party_id bigint;
  room_limit integer := 5;
  clean_game_id text := btrim(coalesce(p_game_id,''));
  clean_starts_at_text text := btrim(coalesce(p_starts_at_text,''));
begin
  if me is null or not public.is_not_banned() then raise exception '请先登录。'; end if;
  if char_length(btrim(coalesce(p_game_name,''))) not between 1 and 30 then raise exception '游戏名称需要填写，最多 30 个字。'; end if;
  if char_length(btrim(coalesce(p_platform,''))) > 20 then raise exception '平台最多 20 个字。'; end if;
  if char_length(btrim(coalesce(p_server_name,''))) > 30 then raise exception '大区或服务器最多 30 个字。'; end if;
  if char_length(btrim(coalesce(p_mode,''))) > 30 then raise exception '游戏模式最多 30 个字。'; end if;
  if char_length(clean_starts_at_text) > 40 then raise exception '开玩时间最多 40 个字。'; end if;
  if p_starts_at is not null and (p_starts_at < now()-interval '2 hours' or p_starts_at > now()+interval '30 days') then raise exception '开玩时间需在现在至 30 天内。'; end if;
  if p_capacity is not null and p_capacity not between 2 and 10 then raise exception '组队人数需在 2 到 10 人之间。'; end if;
  if char_length(clean_game_id) > 60 then raise exception '游戏 ID 最多 60 个字。'; end if;
  if char_length(coalesce(p_note,'')) > 200 then raise exception '补充说明最多 200 个字。'; end if;

  if public.fw_has_active_membership(me) then room_limit := 15; end if;
  perform id from public.profiles where id=me for update;
  if (
    select count(*)
    from public.game_parties
    where captain_id=me and status in ('open','full')
  ) >= room_limit then
    raise exception '当前最多可以创建 % 个组队房间。',room_limit;
  end if;

  insert into public.game_parties(
    captain_id,game_name,platform,server_name,mode,starts_at,starts_at_text,capacity,note,requires_approval
  ) values(
    me,
    btrim(p_game_name),
    btrim(coalesce(p_platform,'')),
    btrim(coalesce(p_server_name,'')),
    btrim(coalesce(p_mode,'')),
    p_starts_at,
    clean_starts_at_text,
    coalesce(p_capacity,5),
    btrim(coalesce(p_note,'')),
    coalesce(p_requires_approval,true)
  ) returning id into party_id;

  insert into public.game_party_members(party_id,user_id,role,state)
  values(party_id,me,'captain','accepted');

  if clean_game_id<>'' then
    insert into public.game_party_contacts(party_id,user_id,game_id)
    values(party_id,me,clean_game_id);
  end if;
  return party_id;
end;
$$;

revoke all on function public.fw_create_game_party(text,text,text,text,timestamptz,integer,text,text,boolean,text) from public,anon,authenticated;
grant execute on function public.fw_create_game_party(text,text,text,text,timestamptz,integer,text,text,boolean,text) to authenticated;

commit;

notify pgrst,'reload schema';
