-- F.w 研究所：观鸟台互动按钮
-- 只新增观鸟台独立互动表，不复用精神广场 reactions 表。

begin;

create table if not exists public.bird_reactions (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.bird_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  created_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'bird_reactions_type_check'
      and conrelid = 'public.bird_reactions'::regclass
  ) then
    alter table public.bird_reactions
      add constraint bird_reactions_type_check
      check (type in ('valid','seen','tissue'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'bird_reactions_post_user_type_key'
      and conrelid = 'public.bird_reactions'::regclass
  ) then
    alter table public.bird_reactions
      add constraint bird_reactions_post_user_type_key
      unique (post_id, user_id, type);
  end if;
end $$;

alter table public.bird_reactions enable row level security;

drop policy if exists "bird_reactions_select_public" on public.bird_reactions;
create policy "bird_reactions_select_public"
  on public.bird_reactions
  for select
  using (true);

drop policy if exists "bird_reactions_insert_own" on public.bird_reactions;
create policy "bird_reactions_insert_own"
  on public.bird_reactions
  for insert
  to authenticated
  with check (
    auth.uid() = user_id
    and public.is_not_banned()
    and type in ('valid','seen','tissue')
    and exists (
      select 1
      from public.bird_posts p
      where p.id = post_id
        and coalesce(p.is_deleted, false) = false
    )
  );

grant select on public.bird_reactions to anon, authenticated;
grant insert on public.bird_reactions to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
