-- F.w 研究所 Supabase 数据库初始化脚本
-- 使用方法：Supabase Dashboard → SQL Editor → New query → 粘贴全文 → Run

create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null default '临时研究员',
  avatar_url text,
  role text not null default 'user' check (role in ('user','admin')),
  is_banned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 500),
  status_tag text not null default '今日无效',
  is_deleted boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 300),
  is_deleted boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.reactions (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('like','same','tissue')),
  created_at timestamptz not null default now(),
  unique(post_id, user_id, type)
);

create index if not exists posts_created_at_idx on public.posts(created_at desc);
create index if not exists comments_post_id_idx on public.comments(post_id);
create index if not exists reactions_post_id_idx on public.reactions(post_id);

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid()
      and role = 'admin'
      and is_banned = false
  );
$$;

create or replace function public.is_not_banned()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid()
      and is_banned = false
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, nickname, avatar_url)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'nickname', ''), '临时研究员 ' || substring(new.id::text, 1, 4)),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.admin_set_user_banned(target_user_id uuid, banned boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Only admin can update user status';
  end if;
  update public.profiles
  set is_banned = banned,
      updated_at = now()
  where id = target_user_id
    and role <> 'admin';
end;
$$;

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.reactions enable row level security;

drop policy if exists "profiles_select_all" on public.profiles;
create policy "profiles_select_all" on public.profiles for select using (true);

drop policy if exists "profiles_update_self" on public.profiles;
create policy "profiles_update_self" on public.profiles for update
using (auth.uid() = id and public.is_not_banned())
with check (auth.uid() = id and public.is_not_banned());

drop policy if exists "posts_select_public" on public.posts;
create policy "posts_select_public" on public.posts for select using (is_deleted = false);

drop policy if exists "posts_insert_user" on public.posts;
create policy "posts_insert_user" on public.posts for insert
with check (auth.uid() = user_id and public.is_not_banned());

drop policy if exists "posts_update_admin" on public.posts;
create policy "posts_update_admin" on public.posts for update
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "comments_select_public" on public.comments;
create policy "comments_select_public" on public.comments for select using (is_deleted = false);

drop policy if exists "comments_insert_user" on public.comments;
create policy "comments_insert_user" on public.comments for insert
with check (auth.uid() = user_id and public.is_not_banned());

drop policy if exists "comments_update_admin" on public.comments;
create policy "comments_update_admin" on public.comments for update
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "reactions_select_public" on public.reactions;
create policy "reactions_select_public" on public.reactions for select using (true);

drop policy if exists "reactions_insert_user" on public.reactions;
create policy "reactions_insert_user" on public.reactions for insert
with check (auth.uid() = user_id and public.is_not_banned());

drop policy if exists "reactions_delete_own" on public.reactions;
create policy "reactions_delete_own" on public.reactions for delete using (auth.uid() = user_id);

revoke update on public.profiles from authenticated;
grant update (nickname, avatar_url, updated_at) on public.profiles to authenticated;
grant select on public.profiles to anon, authenticated;
grant insert, select on public.posts to authenticated;
grant select on public.posts to anon;
grant update on public.posts to authenticated;
grant insert, select on public.comments to authenticated;
grant select on public.comments to anon;
grant update on public.comments to authenticated;
grant insert, select, delete on public.reactions to authenticated;
grant select on public.reactions to anon;
grant execute on function public.admin_set_user_banned(uuid, boolean) to authenticated;

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do update set public = true;

drop policy if exists "avatars_public_read" on storage.objects;
create policy "avatars_public_read" on storage.objects for select using (bucket_id = 'avatars');

drop policy if exists "avatars_user_insert" on storage.objects;
create policy "avatars_user_insert" on storage.objects for insert
with check (bucket_id = 'avatars' and auth.uid()::text = (storage.foldername(name))[1]);

drop policy if exists "avatars_user_update" on storage.objects;
create policy "avatars_user_update" on storage.objects for update
using (bucket_id = 'avatars' and auth.uid()::text = (storage.foldername(name))[1])
with check (bucket_id = 'avatars' and auth.uid()::text = (storage.foldername(name))[1]);
