import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';

const root=resolve(import.meta.dirname,'..');
const read=file=>readFileSync(resolve(root,file),'utf8');
const html=read('index.html');
const app=read('src/app.js');
const api=read('src/admin-api.js');
const css=read('styles.css');
const tauri=JSON.parse(read('src-tauri/tauri.conf.json'));
const cargo=read('src-tauri/Cargo.toml');
const rust=read('src-tauri/src/main.rs');
const updateUi=read('src-tauri/src/update_ui.js');
const workflow=read('../.github/workflows/build-windows-admin.yml');

assert.match(html,/FW管理台/,'页面必须使用独立管理台名称');
assert.match(app,/举报中心/,'管理台必须提供举报中心');
assert.match(app,/问题反馈/,'管理台必须提供问题反馈');
assert.match(app,/用户管理/,'管理台必须提供用户管理');
assert.match(app,/会员管理/,'管理台必须提供会员管理');
assert.match(app,/内容管理/,'管理台必须提供内容管理');
assert.match(app,/处理记录/,'管理台必须提供处理记录');
assert.match(app,/删除被举报内容/,'举报必须支持内容处理');
assert.match(app,/禁言 30 天/,'用户处罚必须支持明确时长');
assert.match(app,/同步到公开处理公告/,'管理操作必须允许选择是否公开');
assert.match(app,/永久删除账号/,'用户管理必须支持安全删除账号');
assert.match(app,/confirmText!==\'永久删除\'/,'删除账号必须要求二次文字确认');
assert.match(app,/显示测试数据/,'管理台必须默认隐藏并允许显示测试数据');
assert.match(app,/树洞帖子/,'内容管理必须覆盖树洞帖子');
assert.match(app,/树洞评论/,'内容管理必须覆盖树洞评论');
assert.match(app,/组队留言/,'内容管理必须覆盖组队留言');
assert.match(app,/最近登录/,'用户详情必须显示最近登录时间');
assert.match(api,/fw_get_current_profile/,'登录后必须从数据库确认管理员角色');
assert.match(api,/admin_list_feedback_tickets/,'反馈必须从正式后台工单读取');
assert.match(api,/p_admin_reply:''/,'反馈处理不得向用户发送回复');
assert.match(api,/admin_list_memberships/,'会员管理必须读取正式会员数据');
assert.match(api,/admin_grant_membership/,'会员管理必须支持增加会员时间');
assert.match(api,/admin_cancel_membership/,'会员管理必须支持取消会员');
assert.doesNotMatch(app,/回复用户|向用户回复|等待用户回复/,'反馈界面不得要求管理员回复用户');
assert.match(api,/admin_moderate_user/,'用户操作必须走受控管理员 RPC');
assert.match(api,/admin_list_bird_posts/,'内容管理必须读取树洞帖子');
assert.match(api,/admin_list_polls/,'内容管理必须读取投票');
assert.match(api,/admin-delete-user/,'账号删除必须走受控服务端函数');
assert.doesNotMatch(api,/service[_-]?role/i,'安装包不得包含 service role 密钥');
assert.match(css,/--bg:#f4f5f7/,'管理台必须使用白色浅灰管理界面');
assert.equal(tauri.productName,'FW管理台');
assert.equal(tauri.version,'6.0.1');
assert.equal(tauri.identifier,'com.fwyanjiusuo.admin');
assert.equal(tauri.app.windows[0].minWidth,1080);
assert.notEqual(tauri.identifier,'com.fwyanjiusuo.desktop','管理台必须使用独立应用标识');
assert.equal(tauri.bundle.createUpdaterArtifacts,true,'管理台必须生成签名更新包');
assert.match(tauri.plugins.updater.endpoints[0],/admin-windows-updater\.json$/,'管理台必须读取独立更新清单');
assert.match(cargo,/tauri-plugin-updater = "2\.10\.1"/,'管理台必须包含签名更新插件');
assert.match(rust,/updater_builder\(\)/,'管理台启动时必须检查新版本');
assert.match(rust,/立即更新/,'管理台必须提供立即更新入口');
assert.match(rust,/app\.restart\(\)/,'更新安装完成后必须自动重启');
assert.match(rust,/正在下载更新/,'更新过程必须显示下载阶段');
assert.match(updateUi,/正在连接/,'更新过程必须显示连接阶段');
assert.match(workflow,/TAURI_SIGNING_PRIVATE_KEY/,'发布流程必须生成签名更新包');
assert.match(workflow,/admin-windows-updater\.json/,'发布流程必须生成管理台更新清单');

console.log('FW管理台静态检查通过。');
