import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('../..',import.meta.url)));
const read=path=>readFileSync(resolve(root,path),'utf8');
const config=JSON.parse(read('src-tauri/tauri.v11.conf.json'));
assert.equal(config.version,'1.1.6');
assert.equal(config.build.frontendDist,'../desktop-v11/dist');
assert.equal(config.build.devUrl,'http://127.0.0.1:1421');
assert.equal(config.app.windows[0].url,'index.html');
assert.match(config.app.windows[0].userAgent,/FWYanjiusuoDesktop\/1\.1\.6/);
assert.doesNotMatch(JSON.stringify(config),/fwyanjiusuo\.com\/index\.html/);
assert.match(config.app.security.csp,/supabase\.co/);

const app=read('desktop-v11/src/app.js');
const auth=read('desktop-v11/src/auth-store.js');
const social=read('desktop-v11/src/social-store.js');
const feed=read('desktop-v11/src/feed-store.js');
const polls=read('desktop-v11/src/poll-store.js');
const bird=read('desktop-v11/src/bird-store.js');
const archive=read('desktop-v11/src/archive-store.js');
const html=read('desktop-v11/index.html');
const theme=read('desktop-v11/public/brand-theme.css');
const rust=read('src-tauri/src/main.rs');
const updateUi=read('src-tauri/src/update_ui.js');
const cargo=read('src-tauri/Cargo.toml');
assert.match(theme,/--bg:#eee9df!important/,'Windows 经典背景色必须保持为旧版米灰');
assert.match(theme,/--paper:#fffdf7!important/,'Windows 经典卡片色必须保持为旧版暖白');
assert.match(theme,/--deep:#181916!important/,'Windows 经典结构色必须保持为近黑色');
assert.match(theme,/--accent:#d97979!important/,'Windows 经典主操作色必须保持为粉色');
assert.match(theme,/Windows 1\.1\.6 本地前端 · 自动更新测速版/);
assert.match(theme,/\.sidebar[\s\S]*background:#181916!important/,'左侧栏必须强制恢复黑色');
assert.match(theme,/\.compose-button[\s\S]*background:#d97979!important/,'发牢骚主按钮必须强制恢复粉色');
assert.match(cargo,/version = "1\.1\.6"/);
assert.match(cargo,/tauri-plugin-updater = "2\.10\.1"/);
assert.match(rust,/updater_builder\(\)/,'更新检查必须使用可配置客户端');
assert.match(rust,/connect_timeout/,'更新器必须有连接超时');
assert.match(rust,/read_timeout/,'更新器必须有读取停滞超时');
assert.doesNotMatch(rust,/UPDATE_TOTAL_TIMEOUT_SECS/,'不能再用总时长超时误杀慢速但仍在传输的下载');
assert.doesNotMatch(rust,/\.timeout\(Duration::from_secs/,'更新器不能再设置总请求超时');
assert.match(rust,/UPDATE_UI_INTERVAL_MS: u64 = 250/,'进度 UI 必须节流，不能每个网络 chunk 都刷新 WebView');
assert.match(rust,/UPDATE_LOG_INTERVAL_SECS: u64 = 5/,'下载日志必须节流，不能每个网络 chunk 都同步写磁盘');
assert.match(rust,/last_ui_at/);
assert.match(rust,/last_log_at/);
assert.match(rust,/first_chunk_at/,'速度计算应从真正收到第一块数据开始');
assert.match(rust,/\.download\(/,'更新器必须拆分下载和安装以显示校验阶段');
assert.doesNotMatch(rust,/download_and_install\(\|_, _\| \{\}, \|\| \{\}\)/,'不能再丢弃下载进度');
assert.match(rust,/download_progress/,'必须记录下载进度日志');
assert.match(rust,/include_str!\("update_ui\.js"\)/,'必须注入更新进度界面');
assert.match(updateUi,/fw-update-bar/);
assert.match(updateUi,/speedBps/);
assert.match(html,/data-view-panel="home"/);
assert.match(html,/data-view-panel="compose"/);
assert.match(html,/data-view-panel="square"/);
assert.match(html,/data-view-panel="rooms"/);
assert.match(html,/data-view-panel="bird"/);
assert.match(html,/data-view-panel="archive"/);
assert.match(html,/data-view-panel="echo"/);
assert.match(html,/data-view-panel="buddy"/);
assert.match(html,/data-chat-messages/);
assert.match(html,/data-buddy-tab="messages"/);
assert.match(html,/data-buddy-tab="friends"/);
assert.match(html,/data-buddy-tab="new"/);
assert.match(html,/data-open-account/);
assert.match(html,/data-auth-view="login"/);
assert.match(html,/data-auth-view="register"/);
assert.match(html,/data-auth-view="profile"/);
assert.match(html,/data-auth-view="profile"[\s\S]*?name="labCode"[^>]*disabled/,'个人资料页的实验品编号必须保持只读');
assert.match(auth,/createClient\(SUPABASE_URL, SUPABASE_ANON_KEY/);
assert.equal((auth.match(/createClient\(/g)||[]).length,1,'Supabase 客户端必须只有一个实例');
assert.match(auth,/client\.auth\.getSession\(\)/);
assert.match(auth,/fw_get_current_profile/);
assert.doesNotMatch(auth,/\.from\(['"]posts['"]\)|\.from\(['"]comments['"]\)|private_messages|buddy_connections/,'首页不能读取内容或私聊数据');
assert.doesNotMatch(app,/setInterval|MutationObserver/,'本地首页不能创建轮询或全局 DOM 监听器');
assert.doesNotMatch(social,/setInterval|MutationObserver/,'回声、搭子和私聊不能恢复轮询或全局 DOM 监听器');
assert.doesNotMatch(feed,/setInterval|MutationObserver/,'精神广场不能恢复轮询或全局 DOM 监听器');
assert.match(feed,/desktop-v11-square/);
assert.match(feed,/reply_to_comment_id/);
assert.match(feed,/reply_to_user_id/);
assert.match(feed,/parent_comment_id/);
assert.match(feed,/fw_delete_own_post/);
assert.match(feed,/fw_delete_own_comment/);
assert.match(feed,/fw_submit_report/);
assert.match(feed,/chat-media/);
assert.match(feed,/FW_MEDIA_IMAGE/);
assert.match(feed,/FW_USER_STICKER/);
assert.match(feed,/content\.length>500/);
assert.match(feed,/content\.length>300/);
assert.doesNotMatch(polls,/setInterval|MutationObserver/);
assert.match(polls,/desktop-v11-polls/);
assert.match(polls,/fw_create_poll/);
assert.match(polls,/fw_vote_poll/);
assert.match(polls,/fw_add_poll_option/);
assert.match(polls,/fw_delete_my_poll_option/);
assert.match(polls,/fw_promote_poll_to_official/);
assert.match(polls,/fw_poll_vote_stats/);
assert.match(polls,/fw_my_poll_votes/);
assert.match(polls,/fw_my_poll_daily_count/);
assert.doesNotMatch(bird,/setInterval|MutationObserver/);
assert.match(bird,/desktop-v11-bird/);
assert.match(bird,/bird_posts/);
assert.match(bird,/bird_comments/);
assert.match(bird,/bird_reactions/);
assert.match(bird,/fw_delete_own_bird_post/);
assert.match(bird,/fw_delete_own_bird_comment/);
assert.match(bird,/chat-media/);
assert.match(bird,/files\.length>20/);
assert.match(bird,/cleanContent\.length>5000/);
assert.doesNotMatch(archive,/setInterval|MutationObserver|\.channel\(/);
assert.match(archive,/lastMonday/);
assert.match(archive,/yesterday/);
assert.match(archive,/String\(reaction\.user_id\)===String\(post\.user_id\)/);
assert.match(archive,/\['like','same','tissue'\]/);
assert.match(archive,/\.limit\(1000\)/);
assert.match(social,/desktop-v11-unread-/);
assert.match(social,/desktop-v11-chat-/);
assert.match(social,/\.eq\('type',PRIVATE_TYPE\)/);
assert.match(social,/\.in\('type',ECHO_TYPES\)/);
assert.match(social,/fw_send_private_message_to_user/);
assert.match(social,/fw_get_or_create_conversation/);
assert.match(social,/fw_search_profiles/);
assert.match(social,/fw_respond_friendship/);
assert.match(app,/contentRequests:0/);
assert.match(app,/fixedProfileCode\|\|Boolean\(next\.busy\)/);
assert.doesNotMatch(app,/location\.href|window\.location\.replace|fwyanjiusuo\.com/);
console.log('Windows 1.1.6 updater speed verification and local frontend checks passed');
