import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('../..',import.meta.url)));
const read=path=>readFileSync(resolve(root,path),'utf8');
const config=JSON.parse(read('src-tauri/tauri.v11.conf.json'));
assert.equal(config.version,'1.1.0');
assert.equal(config.build.frontendDist,'../desktop-v11/dist');
assert.equal(config.build.devUrl,'http://127.0.0.1:1421');
assert.equal(config.app.windows[0].url,'index.html');
assert.match(config.app.windows[0].userAgent,/FWYanjiusuoDesktop\/1\.1\.0/);
assert.doesNotMatch(JSON.stringify(config),/fwyanjiusuo\.com\/index\.html/);
assert.match(config.app.security.csp,/supabase\.co/);

const app=read('desktop-v11/src/app.js');
const auth=read('desktop-v11/src/auth-store.js');
const social=read('desktop-v11/src/social-store.js');
const feed=read('desktop-v11/src/feed-store.js');
const polls=read('desktop-v11/src/poll-store.js');
const bird=read('desktop-v11/src/bird-store.js');
const archive=read('desktop-v11/src/archive-store.js');
const html=read('desktop-v11/index.html');
assert.match(html,/data-view-panel="home"/);
assert.match(html,/data-view-panel="compose"/);
assert.match(html,/data-view-panel="square"/);
assert.match(html,/data-view-panel="rooms"/);
assert.match(html,/data-view-panel="bird"/);
assert.match(html,/data-view-panel="archive"/);
assert.match(html,/data-view-panel="echo"/);
assert.match(html,/data-view-panel="buddy"/);
assert.match(html,/data-chat-messages/);
assert.match(html,/data-buddy-tab="messages"/);
assert.match(html,/data-buddy-tab="friends"/);
assert.match(html,/data-buddy-tab="new"/);
assert.match(html,/data-open-account/);
assert.match(html,/data-auth-view="login"/);
assert.match(html,/data-auth-view="register"/);
assert.match(html,/data-auth-view="profile"/);
assert.match(html,/data-auth-view="profile"[\s\S]*?name="labCode"[^>]*disabled/,'个人资料页的实验品编号必须保持只读');
assert.match(auth,/createClient\(SUPABASE_URL, SUPABASE_ANON_KEY/);
assert.equal((auth.match(/createClient\(/g)||[]).length,1,'Supabase 客户端必须只有一个实例');
assert.match(auth,/client\.auth\.getSession\(\)/);
assert.match(auth,/fw_get_current_profile/);
assert.doesNotMatch(auth,/\.from\(['"]posts['"]\)|\.from\(['"]comments['"]\)|private_messages|buddy_connections/,'第一阶段首页不能读取内容或私聊数据');
assert.doesNotMatch(app,/setInterval|MutationObserver/,'本地首页不能创建轮询或全局 DOM 监听器');
assert.doesNotMatch(social,/setInterval|MutationObserver/,'回声、搭子和私聊不能恢复轮询或全局 DOM 监听器');
assert.doesNotMatch(feed,/setInterval|MutationObserver/,'精神广场不能恢复轮询或全局 DOM 监听器');
assert.match(feed,/desktop-v11-square/,'精神广场必须只在进入页面后启用本地实时通道');
assert.match(feed,/reply_to_comment_id/,'评论回复必须记录实际回复对象');
assert.match(feed,/reply_to_user_id/,'评论回复必须记录被回复用户');
assert.match(feed,/parent_comment_id/,'评论回复必须保留楼层根评论');
assert.match(feed,/fw_delete_own_post/);
assert.match(feed,/fw_delete_own_comment/);
assert.match(feed,/fw_submit_report/);
assert.match(feed,/chat-media/,'帖子和评论图片继续复用现有媒体桶');
assert.match(feed,/FW_MEDIA_IMAGE/);
assert.match(feed,/FW_USER_STICKER/);
assert.match(feed,/content\.length>500/);
assert.match(feed,/content\.length>300/);
assert.doesNotMatch(polls,/setInterval|MutationObserver/,'学术研讨不能使用轮询或全局 DOM 监听器');
assert.match(polls,/desktop-v11-polls/,'学术研讨只在打开页面时启用实时通道');
assert.match(polls,/fw_create_poll/);
assert.match(polls,/fw_vote_poll/);
assert.match(polls,/fw_add_poll_option/);
assert.match(polls,/fw_delete_my_poll_option/);
assert.match(polls,/fw_promote_poll_to_official/);
assert.match(polls,/fw_poll_vote_stats/);
assert.match(polls,/fw_my_poll_votes/);
assert.match(polls,/fw_my_poll_daily_count/);
assert.doesNotMatch(bird,/setInterval|MutationObserver/,'观鸟台不能使用轮询或全局 DOM 监听器');
assert.match(bird,/desktop-v11-bird/,'观鸟台只在打开页面时启用实时通道');
assert.match(bird,/bird_posts/);
assert.match(bird,/bird_comments/);
assert.match(bird,/bird_reactions/);
assert.match(bird,/fw_delete_own_bird_post/);
assert.match(bird,/fw_delete_own_bird_comment/);
assert.match(bird,/chat-media/);
assert.match(bird,/files\.length>20/);
assert.match(bird,/cleanContent\.length>5000/);
assert.doesNotMatch(archive,/setInterval|MutationObserver|\.channel\(/,'废话档案不能轮询或常驻订阅');
assert.match(archive,/lastMonday/);
assert.match(archive,/yesterday/);
assert.match(archive,/String\(reaction\.user_id\)===String\(post\.user_id\)/,'榜单必须排除自己给自己的互动');
assert.match(archive,/\['like','same','tissue'\]/);
assert.match(archive,/\.limit\(1000\)/);
assert.match(social,/desktop-v11-unread-/,'必须只有一个社交未读实时通道');
assert.match(social,/desktop-v11-chat-/,'私聊必须使用单会话实时订阅');
assert.match(social,/\.eq\('type',PRIVATE_TYPE\)/,'私聊未读必须独立于回声');
assert.match(social,/\.in\('type',ECHO_TYPES\)/,'回声只读取明确的回声类型');
assert.match(social,/fw_send_private_message_to_user/);
assert.match(social,/fw_get_or_create_conversation/);
assert.match(social,/fw_search_profiles/);
assert.match(social,/fw_respond_friendship/);
assert.match(app,/contentRequests:0/);
assert.match(app,/fixedProfileCode\|\|Boolean\(next\.busy\)/,'账号状态更新不能解锁个人资料页的实验品编号');
assert.doesNotMatch(app,/location\.href|window\.location\.replace|fwyanjiusuo\.com/,'本地导航不能回跳网页页面');
console.log('Windows 1.1.0 local social migration static checks passed');
