import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const root=resolve(fileURLToPath(new URL('../..',import.meta.url)));
const read=path=>readFileSync(resolve(root,path),'utf8');
const config=JSON.parse(read('src-tauri/tauri.v11.conf.json'));
assert.equal(config.version,'1.1.14');
assert.equal(config.build.frontendDist,'../desktop-v11/dist');
assert.equal(config.build.devUrl,'http://127.0.0.1:1421');
assert.equal(config.app.windows[0].url,'index.html');
assert.match(config.app.windows[0].userAgent,/FWYanjiusuoDesktop\/1\.1\.14/);
assert.doesNotMatch(JSON.stringify(config),/fwyanjiusuo\.com\/index\.html/);
assert.match(config.app.security.csp,/supabase\.co/);
assert.match(config.app.security.csp,/media-src/,'本地客户端必须允许 Supabase 媒体播放');

const app=read('desktop-v11/src/app.js');
const auth=read('desktop-v11/src/auth-store.js');
const social=read('desktop-v11/src/social-store.js');
const feed=read('desktop-v11/src/feed-store.js');
const polls=read('desktop-v11/src/poll-store.js');
const bird=read('desktop-v11/src/bird-store.js');
const archive=read('desktop-v11/src/archive-store.js');
const alignment=read('desktop-v11/src/feature-alignment.js');
const composeUi=read('desktop-v11/src/compose-ui-alignment.js');
const squareScroll=read('desktop-v11/src/square-scroll-fix.js');
const persistentCache=read('desktop-v11/src/desktop-persistent-cache.js');
const supplementalCache=read('desktop-v11/src/supplemental-cache.js');
const persistentRust=read('src-tauri/src/persistent_cache.rs');
const navFix=read('desktop-v11/src/alignment-nav-fix.js');
const html=read('desktop-v11/index.html');
const theme=read('desktop-v11/public/brand-theme.css');
const rust=read('src-tauri/src/main.rs');
const updateUi=read('src-tauri/src/update_ui.js');
const cargo=read('src-tauri/Cargo.toml');
assert.match(theme,/--bg:#eee9df!important/,'Windows 经典背景色必须保持为旧版米灰');
assert.match(theme,/--paper:#fffdf7!important/,'Windows 经典卡片色必须保持为旧版暖白');
assert.match(theme,/--deep:#181916!important/,'Windows 经典结构色必须保持为近黑色');
assert.match(theme,/--accent:#d97979!important/,'Windows 经典主操作色必须保持为粉色');
assert.match(theme,/\.sidebar[\s\S]*background:#181916!important/,'左侧栏必须强制恢复黑色');
assert.match(theme,/\.compose-button[\s\S]*background:#d97979!important/,'发牢骚主按钮必须强制恢复粉色');
assert.match(theme,/\.status-options/,'旧发帖状态选择必须在桌面端被隐藏');
assert.match(theme,/\.square-post \.post-meta>span:first-child/,'精神广场卡片不得再显示旧状态标签');
assert.match(theme,/\.detail-post \.post-meta>span:first-child/,'帖子详情不得再显示旧状态标签');
assert.match(cargo,/version = "1\.1\.14"/);
assert.match(cargo,/tauri-plugin-updater = "2\.10\.1"/);
assert.match(cargo,/rusqlite = \{ version = "0\.32", features = \["bundled"\] \}/,'持久缓存必须使用内置 SQLite，不能依赖用户额外安装数据库');
assert.match(rust,/mod persistent_cache;/,'Rust 主程序必须注册持久缓存模块');
assert.match(rust,/persistent_cache::desktop_persistent_cache_read/,'必须注册持久缓存读取命令');
assert.match(rust,/persistent_cache::desktop_persistent_cache_write/,'必须注册持久缓存写入命令');
assert.match(persistentRust,/CACHE_FOLDER: &str = "Cache"/,'默认缓存目录必须命名为 Cache');
assert.match(persistentRust,/std::env::current_exe\(\)/,'缓存必须先以当前 exe 所在安装目录为基准');
assert.match(persistentRust,/parent\.join\(CACHE_FOLDER\)/,'缓存必须优先创建在安装目录下');
assert.match(persistentRust,/app_data_dir\(\)/,'安装目录不可写时必须自动回退 AppData');
assert.match(persistentRust,/CACHE_DB_FILE: &str = "fw-cache\.db"/,'持久缓存必须使用固定 SQLite 文件');
assert.match(persistentRust,/CREATE TABLE IF NOT EXISTS cache_entries/,'SQLite 必须初始化统一缓存表');
assert.match(persistentRust,/journal_mode=WAL/,'SQLite 必须启用 WAL 以减少读写互相阻塞');
assert.match(persistentCache,/desktop_persistent_cache_read/,'前端缓存桥必须读取 Rust SQLite');
assert.match(persistentCache,/desktop_persistent_cache_write/,'前端缓存桥必须写入 Rust SQLite');
assert.match(persistentCache,/savedAt:Date\.now\(\)/,'缓存条目必须记录本地保存时间');

assert.match(feed,/desktop-persistent-cache\.js/,'精神广场必须接入持久缓存桥');
assert.match(feed,/desktopCache\.read\('square'/,'精神广场启动时必须先读本地缓存');
assert.match(feed,/desktopCache\.write\('square'/,'精神广场联网成功后必须回写本地缓存');
assert.match(social,/desktop-persistent-cache\.js/,'回声、搭子、私聊、表情和红点必须接入持久缓存桥');
assert.match(social,/desktopCache\.read\('echo'/,'回声必须支持跨重启缓存');
assert.match(social,/desktopCache\.write\('echo'/,'回声必须同步更新本地缓存');
assert.match(social,/desktopCache\.read\('buddy'/,'搭子列表必须支持跨重启缓存');
assert.match(social,/desktopCache\.write\('buddy'/,'搭子列表必须同步更新本地缓存');
assert.match(social,/desktopCache\.read\('chat'/,'私聊必须先读本地历史');
assert.match(social,/desktopCache\.write\('chat'/,'私聊必须把最新历史写回本地');
assert.match(social,/rows\.slice\(-200\)/,'每个私聊本地最多保留最近 200 条，避免无限增长');
assert.match(social,/desktopCache\.read\('stickers'/,'我的表情必须支持跨重启缓存');
assert.match(social,/desktopCache\.write\('stickers'/,'我的表情必须同步更新本地缓存');
assert.match(social,/desktopCache\.read\('badges'/,'通知红点必须支持快速缓存恢复');
assert.match(social,/desktopCache\.write\('badges'/,'通知红点刷新后必须更新缓存');
assert.match(auth,/desktop-persistent-cache\.js/,'账号资料必须接入统一持久缓存');
assert.match(auth,/desktopCache\.read\('profile'/,'账号资料必须支持 SQLite 跨重启缓存');
assert.match(auth,/desktopCache\.write\('profile'/,'账号资料更新后必须回写 SQLite');
assert.match(polls,/desktop-persistent-cache\.js/,'学术研讨必须接入统一持久缓存');
assert.match(polls,/desktopCache\.read\('polls'/,'学术研讨必须先读本地缓存');
assert.match(polls,/desktopCache\.write\('polls'/,'学术研讨必须回写本地缓存');
assert.match(bird,/desktop-persistent-cache\.js/,'观鸟台必须接入统一持久缓存');
assert.match(bird,/desktopCache\.read\('bird','public'/,'观鸟台必须先读本地缓存');
assert.match(bird,/desktopCache\.write\('bird','public'/,'观鸟台必须回写本地缓存');
assert.match(archive,/desktop-persistent-cache\.js/,'废话档案必须接入统一持久缓存');
assert.match(archive,/desktopCache\.read\('archive','public'/,'废话档案必须先读本地缓存');
assert.match(archive,/desktopCache\.write\('archive','public'/,'废话档案必须回写本地缓存');
assert.match(navFix,/supplemental-cache\.js/,'桌面端必须加载辅助公开数据缓存层');
assert.match(supplementalCache,/desktopCache\.read\('moderation','public'/,'公开处理公告必须支持本地缓存');
assert.match(supplementalCache,/desktopCache\.read\('public_profile','public'/,'公开资料卡必须支持本地缓存');
assert.doesNotMatch(supplementalCache,/MutationObserver|setInterval/,'辅助缓存层不能引入全局轮询或 DOM 监听器');

assert.match(rust,/updater_builder\(\)/,'更新检查必须使用可配置客户端');
assert.match(rust,/connect_timeout/,'更新器必须有连接超时');
assert.match(rust,/read_timeout/,'更新器必须有读取停滞超时');
assert.doesNotMatch(rust,/UPDATE_TOTAL_TIMEOUT_SECS/,'不能再用总时长超时误杀慢速但仍在传输的下载');
assert.doesNotMatch(rust,/\.timeout\(Duration::from_secs/,'更新器不能再设置总请求超时');
assert.match(rust,/UPDATE_UI_INTERVAL_MS: u64 = 250/,'进度 UI 必须节流，不能每个网络 chunk 都刷新 WebView');
assert.match(rust,/UPDATE_LOG_INTERVAL_SECS: u64 = 5/,'下载日志必须节流，不能每个网络 chunk 都同步写磁盘');
assert.match(rust,/\.no_proxy\(\)/,'兼容直连模式必须绕过系统代理');
assert.match(rust,/\.http1_only\(\)/,'兼容直连模式必须固定 HTTP\/1.1');
assert.match(rust,/Ipv4Addr::UNSPECIFIED/,'兼容直连模式必须固定 IPv4');
assert.match(rust,/check_system_start/,'更新检查必须优先使用 Windows 系统网络');
assert.match(rust,/fallback_direct_check_start/,'系统网络下载失败后必须自动切换兼容直连');
assert.match(rust,/if network_mode == UPDATE_MODE_SYSTEM[\s\S]*check_for_updates_direct_auto/,'只有系统网络下载失败时才进入兼容直连兜底');
assert.doesNotMatch(rust,/fallback_system_check_start/,'不能继续使用直连优先、系统网络兜底的旧顺序');
assert.match(rust,/优先使用 Windows 系统网络/,'更新提示必须明确系统网络优先');
assert.match(rust,/UPDATE_MODE_DIRECT/);
assert.match(rust,/UPDATE_MODE_SYSTEM/);
assert.match(rust,/network_mode/,'更新日志和进度必须记录当前网络通道');
assert.match(rust,/last_ui_at/);
assert.match(rust,/last_log_at/);
assert.match(rust,/first_chunk_at/,'速度计算应从真正收到第一块数据开始');
assert.match(rust,/\.download\(/,'更新器必须拆分下载和安装以显示校验阶段');
assert.doesNotMatch(rust,/download_and_install\(\|_, _\| \{\}, \|\| \{\}\)/,'不能再丢弃下载进度');
assert.match(rust,/download_progress/,'必须记录下载进度日志');
assert.match(rust,/include_str!\("update_ui\.js"\)/,'必须注入更新进度界面');
assert.match(updateUi,/fw-update-bar/);
assert.match(updateUi,/speedBps/);
assert.match(html,/data-view-panel="home"/);
assert.match(html,/data-view-panel="compose"/);
assert.match(html,/data-view-panel="square"/);
assert.match(html,/data-view-panel="rooms"/);
assert.match(html,/data-view-panel="bird"/);
assert.match(html,/data-view-panel="archive"/);
assert.match(html,/data-view-panel="echo"/);
assert.match(html,/data-view-panel="buddy"/);
assert.match(html,/data-chat-messages/);
assert.match(html,/data-buddy-tab="messages"/);
assert.match(html,/data-buddy-tab="friends"/);
assert.match(html,/data-buddy-tab="new"/);
assert.match(html,/data-open-account/);
assert.match(html,/data-auth-view="login"/);
assert.match(html,/data-auth-view="register"/);
assert.match(html,/data-auth-view="profile"/);
assert.match(html,/feature-alignment\.js/,'P0-P2 功能对齐层必须随本地客户端加载');
assert.doesNotMatch(html,/刚刚有人说/,'Windows 首页不恢复网页端实时帖子流');
assert.match(html,/data-auth-view="profile"[\s\S]*?name="labCode"[^>]*disabled/,'个人资料页的实验品编号必须保持只读');
assert.match(navFix,/compose-ui-alignment\.js/,'桌面端必须加载网页版风格的发布工具收起层');
assert.match(navFix,/square-scroll-fix\.js/,'桌面端必须加载精神广场双栏滚动修复层');
assert.match(composeUi,/data-compose-compact-emoji/,'发布页必须提供独立的表情圆形按钮');
assert.match(composeUi,/data-compose-compact-media/,'发布页必须提供独立的加号媒体按钮');
assert.match(composeUi,/\.media-tools\{display:none!important\}/,'旧的大号添加图片\/视频工具行必须收起');
assert.match(composeUi,/pickerOpen/,'我的表情面板必须按需展开而不是常驻');
assert.match(composeUi,/\[data-compose-image\]/,'加号必须继续复用现有图片\/视频上传能力');
assert.match(squareScroll,/Windows 1\.1\.14 本地前端 · 系统网络优先更新版/,'右下角版本标识必须更新');
assert.match(squareScroll,/square-scroll-locked/,'精神广场必须锁住整页滚动');
assert.match(squareScroll,/\.square-feed\{min-height:0;overflow-y:auto/,'左侧帖子列表必须独立滚动');
assert.match(squareScroll,/\.detail-scroll\{height:100%;min-height:0;overflow-y:auto/,'右侧详情必须独立滚动');
assert.match(squareScroll,/attributeFilter:\['data-view'\]/,'滚动锁监听必须只观察 data-view，不能监听整棵 DOM');
assert.match(auth,/createClient\(SUPABASE_URL, SUPABASE_ANON_KEY/);
assert.equal((auth.match(/createClient\(/g)||[]).length,1,'Supabase 客户端必须只有一个实例');
assert.match(auth,/client\.auth\.getSession\(\)/);
assert.match(auth,/fw_get_current_profile/);
assert.doesNotMatch(auth,/\.from\(['"]posts['"]\)|\.from\(['"]comments['"]\)|private_messages|buddy_connections/,'首页不能读取内容或私聊数据');
assert.doesNotMatch(app,/setInterval|MutationObserver/,'本地首页不能创建轮询或全局 DOM 监听器');
assert.doesNotMatch(social,/setInterval|MutationObserver/,'回声、搭子和私聊不能恢复轮询或全局 DOM 监听器');
assert.doesNotMatch(feed,/setInterval|MutationObserver/,'精神广场数据层不能恢复轮询或全局 DOM 监听器');
assert.match(feed,/desktop-v11-square/);
assert.match(feed,/reply_to_comment_id/);
assert.match(feed,/reply_to_user_id/);
assert.match(feed,/parent_comment_id/);
assert.match(feed,/fw_delete_own_post/);
assert.match(feed,/fw_delete_own_comment/);
assert.match(feed,/fw_submit_report/);
assert.match(feed,/chat-media/);
assert.match(feed,/FW_MEDIA_IMAGE/);
assert.match(feed,/FW_MEDIA_VIDEO/,'精神广场必须支持视频媒体标记');
assert.match(feed,/FW_USER_STICKER/);
assert.match(feed,/uploadMedia/,'帖子和评论必须共用图片\/视频上传逻辑');
assert.match(feed,/20\*1024\*1024/,'视频上限必须保持 20MB');
assert.match(feed,/content\.length>500/);
assert.match(feed,/content\.length>300/);
assert.doesNotMatch(polls,/setInterval|MutationObserver/);
assert.match(polls,/desktop-v11-polls/);
assert.match(polls,/fw_create_poll/);
assert.match(polls,/fw_vote_poll/);
assert.match(polls,/fw_add_poll_option/);
assert.match(polls,/fw_delete_my_poll_option/);
assert.match(polls,/fw_promote_poll_to_official/);
assert.match(polls,/fw_poll_vote_stats/);
assert.match(polls,/fw_my_poll_votes/);
assert.match(polls,/fw_my_poll_daily_count/);
assert.doesNotMatch(bird,/setInterval|MutationObserver/);
assert.match(bird,/desktop-v11-bird/);
assert.match(bird,/bird_posts/);
assert.match(bird,/bird_comments/);
assert.match(bird,/bird_reactions/);
assert.match(bird,/fw_delete_own_bird_post/);
assert.match(bird,/fw_delete_own_bird_comment/);
assert.match(bird,/chat-media/);
assert.match(bird,/files\.length>20/);
assert.match(bird,/cleanContent\.length>5000/);
assert.doesNotMatch(archive,/setInterval|MutationObserver|\.channel\(/);
assert.match(archive,/lastMonday/);
assert.match(archive,/yesterday/);
assert.match(archive,/String\(reaction\.user_id\)===String\(post\.user_id\)/);
assert.match(archive,/\['like','same','tissue'\]/);
assert.match(archive,/\.limit\(1000\)/);
assert.match(social,/desktop-v11-unread-/);
assert.match(social,/desktop-v11-chat-/);
assert.match(social,/\.eq\('type',PRIVATE_TYPE\)/);
assert.match(social,/\.in\('type',ECHO_TYPES\)/);
assert.match(social,/fw_send_private_message_to_user/);
assert.match(social,/fw_get_or_create_conversation/);
assert.match(social,/fw_search_profiles/);
assert.match(social,/fw_respond_friendship/);
assert.match(alignment,/FW_MEDIA_VIDEO/,'对齐层必须渲染和发送视频');
assert.match(alignment,/data-align-chat-media/,'搭子私聊必须提供媒体入口');
assert.match(alignment,/data-align-report-comment/,'评论必须提供举报入口');
assert.match(alignment,/fw_block_user/,'搭子必须支持拉黑');
assert.match(alignment,/data-align-report-user/,'搭子必须支持举报');
assert.match(alignment,/data-align-view-profile/,'搭子必须支持查看资料');
assert.match(alignment,/moderation_logs/,'普通用户处理公告必须读取公开处理记录');
assert.match(alignment,/入馆须知/,'Windows 必须提供入馆须知');
assert.match(alignment,/隐私政策/,'Windows 必须提供隐私政策');
assert.doesNotMatch(alignment,/data-admin-panel|admin_list_profiles|站长处理面板/,'Windows 普通客户端不迁入管理员后台');
assert.match(app,/contentRequests:0/);
assert.match(app,/fixedProfileCode\|\|Boolean\(next\.busy\)/);
assert.doesNotMatch(app,/location\.href|window\.location\.replace|fwyanjiusuo\.com/);
console.log('Windows 1.1.14 system-network-first updater and global cache checks passed');
