-- FW管理台：反馈工单、组队管理和管理员专用读取接口。
-- 所有高权限操作都在数据库再次校验 public.is_admin()；客户端只使用 publishable key。

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists public.feedback_tickets (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  source_key text not null unique,
  category text not null default '其他',
  content text not null check (char_length(btrim(content)) between 1 and 2000),
  version text,
  platform text,
  status text not null default 'new' check (status in ('new','in_progress','waiting_user','resolved','closed')),
  priority text not null default 'normal' check (priority in ('low','normal','medium','high')),
  admin_reply text,
  internal_note text,
  source_event_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  handled_at timestamptz,
  handled_by uuid references public.profiles(id) on delete set null
);

create index if not exists feedback_tickets_status_created_idx
  on public.feedback_tickets(status, created_at desc);
create index if not exists feedback_tickets_user_created_idx
  on public.feedback_tickets(user_id, created_at desc);

alter table public.feedback_tickets enable row level security;
revoke all on table public.feedback_tickets from public, anon, authenticated;
revoke all on sequence public.feedback_tickets_id_seq from public, anon, authenticated;

drop policy if exists feedback_tickets_admin_select on public.feedback_tickets;
create policy feedback_tickets_admin_select
  on public.feedback_tickets for select
  to authenticated
  using ((select public.is_admin()));

drop policy if exists feedback_tickets_admin_update on public.feedback_tickets;
create policy feedback_tickets_admin_update
  on public.feedback_tickets for update
  to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

grant select, update on table public.feedback_tickets to authenticated;

create or replace function private.capture_fw_feedback()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  payload jsonb;
  event_time timestamptz;
  fingerprint text;
begin
  payload := new.raw_user_meta_data -> 'fw_feedback';
  if payload is null or jsonb_typeof(payload) <> 'object' then
    return new;
  end if;
  if old.raw_user_meta_data -> 'fw_feedback' is not distinct from payload then
    return new;
  end if;
  if btrim(coalesce(payload ->> 'content','')) = '' then
    return new;
  end if;

  begin
    event_time := nullif(payload ->> 'createdAt','')::timestamptz;
  exception when others then
    event_time := now();
  end;
  event_time := coalesce(event_time, now());
  fingerprint := md5(new.id::text || '|' || coalesce(payload ->> 'createdAt','') || '|' || coalesce(payload ->> 'content',''));

  insert into public.feedback_tickets(user_id,source_key,category,content,version,platform,source_event_at,created_at)
  values(
    new.id,
    fingerprint,
    left(coalesce(nullif(btrim(payload ->> 'category'),''),'其他'),60),
    left(btrim(payload ->> 'content'),2000),
    left(nullif(btrim(payload ->> 'version'),''),60),
    left(nullif(btrim(payload ->> 'platform'),''),60),
    event_time,
    event_time
  )
  on conflict (source_key) do nothing;
  return new;
exception when others then
  -- 反馈汇总失败不能阻断用户资料更新或登录流程。
  return new;
end;
$$;

revoke all on function private.capture_fw_feedback() from public, anon, authenticated;

drop trigger if exists fw_capture_feedback_after_auth_update on auth.users;
create trigger fw_capture_feedback_after_auth_update
  after update of raw_user_meta_data on auth.users
  for each row execute function private.capture_fw_feedback();

insert into public.feedback_tickets(user_id,source_key,category,content,version,platform,source_event_at,created_at)
select
  u.id,
  md5(u.id::text || '|' || coalesce(u.raw_user_meta_data -> 'fw_feedback' ->> 'createdAt','') || '|' || coalesce(u.raw_user_meta_data -> 'fw_feedback' ->> 'content','')),
  left(coalesce(nullif(btrim(u.raw_user_meta_data -> 'fw_feedback' ->> 'category'),''),'其他'),60),
  left(btrim(u.raw_user_meta_data -> 'fw_feedback' ->> 'content'),2000),
  left(nullif(btrim(u.raw_user_meta_data -> 'fw_feedback' ->> 'version'),''),60),
  left(nullif(btrim(u.raw_user_meta_data -> 'fw_feedback' ->> 'platform'),''),60),
  u.updated_at,
  u.updated_at
from auth.users u
where jsonb_typeof(u.raw_user_meta_data -> 'fw_feedback') = 'object'
  and btrim(coalesce(u.raw_user_meta_data -> 'fw_feedback' ->> 'content','')) <> ''
on conflict (source_key) do nothing;

drop function if exists public.admin_list_feedback_tickets();
create function public.admin_list_feedback_tickets()
returns table(
  id bigint,
  user_id uuid,
  nickname text,
  email text,
  category text,
  content text,
  version text,
  platform text,
  status text,
  priority text,
  admin_reply text,
  internal_note text,
  created_at timestamptz,
  updated_at timestamptz,
  handled_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'Only admin can read feedback tickets';
  end if;
  return query
    select f.id,f.user_id,p.nickname,u.email,f.category,f.content,f.version,f.platform,
           f.status,f.priority,f.admin_reply,f.internal_note,f.created_at,f.updated_at,f.handled_at
    from public.feedback_tickets f
    left join public.profiles p on p.id=f.user_id
    left join auth.users u on u.id=f.user_id
    order by
      case f.priority when 'high' then 1 when 'medium' then 2 when 'normal' then 3 else 4 end,
      case f.status when 'new' then 1 when 'in_progress' then 2 when 'waiting_user' then 3 else 4 end,
      f.created_at desc
    limit 300;
end;
$$;

drop function if exists public.admin_update_feedback_ticket(bigint,text,text,text,text);
create function public.admin_update_feedback_ticket(
  p_ticket_id bigint,
  p_status text,
  p_priority text,
  p_admin_reply text default '',
  p_internal_note text default ''
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  ticket_user uuid;
  old_reply text;
  clean_reply text := left(btrim(coalesce(p_admin_reply,'')),500);
begin
  if not public.is_admin() then
    raise exception 'Only admin can update feedback tickets';
  end if;
  if p_status not in ('new','in_progress','waiting_user','resolved','closed') then
    raise exception 'Invalid feedback status';
  end if;
  if p_priority not in ('low','normal','medium','high') then
    raise exception 'Invalid feedback priority';
  end if;

  select f.user_id,coalesce(f.admin_reply,'') into ticket_user,old_reply
  from public.feedback_tickets f where f.id=p_ticket_id for update;
  if not found then
    raise exception 'Feedback ticket not found';
  end if;

  update public.feedback_tickets
  set status=p_status,
      priority=p_priority,
      admin_reply=nullif(clean_reply,''),
      internal_note=nullif(left(btrim(coalesce(p_internal_note,'')),500),''),
      updated_at=now(),
      handled_at=case when p_status in ('resolved','closed') then now() else null end,
      handled_by=auth.uid()
  where id=p_ticket_id;

  if ticket_user is not null and clean_reply <> '' and clean_reply is distinct from old_reply then
    insert into public.notifications(user_id,actor_id,type,target_type,target_id,content,is_read,created_at)
    values(ticket_user,auth.uid(),'system','feedback',p_ticket_id::text,'管理员回复了你的反馈：' || clean_reply,false,now());
  end if;

  perform public.fw_log_moderation('feedback',p_ticket_id::text,ticket_user,'feedback_update',
    '反馈状态更新为 ' || p_status,null,false,null);
end;
$$;

drop function if exists public.admin_list_game_parties();
create function public.admin_list_game_parties()
returns table(
  id bigint,
  captain_id uuid,
  captain_name text,
  game_name text,
  mode text,
  starts_at_text text,
  capacity integer,
  member_count integer,
  note text,
  status text,
  requires_approval boolean,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'Only admin can read game parties';
  end if;
  return query
    select g.id,g.captain_id,p.nickname,g.game_name,g.mode,g.starts_at_text,g.capacity,g.member_count,
           g.note,g.status,g.requires_approval,g.created_at
    from public.game_parties g
    left join public.profiles p on p.id=g.captain_id
    order by g.created_at desc
    limit 200;
end;
$$;

drop function if exists public.admin_delete_game_party(bigint,text);
create function public.admin_delete_game_party(p_party_id bigint,p_reason text default '组队房间违规，管理员删除')
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  owner_id uuid;
  party_name text;
begin
  if not public.is_admin() then
    raise exception 'Only admin can delete game parties';
  end if;
  select g.captain_id,g.game_name into owner_id,party_name from public.game_parties g where g.id=p_party_id;
  if not found then
    raise exception 'Game party not found';
  end if;
  delete from public.game_parties where id=p_party_id;
  perform public.fw_log_moderation('game_party',p_party_id::text,owner_id,'delete_game_party',
    coalesce(nullif(btrim(p_reason),''),'组队房间违规，管理员删除') || '（' || coalesce(party_name,'未命名游戏') || '）',null,false,null);
end;
$$;

revoke all on function public.admin_list_feedback_tickets() from public, anon, authenticated;
revoke all on function public.admin_update_feedback_ticket(bigint,text,text,text,text) from public, anon, authenticated;
revoke all on function public.admin_list_game_parties() from public, anon, authenticated;
revoke all on function public.admin_delete_game_party(bigint,text) from public, anon, authenticated;

grant execute on function public.admin_list_feedback_tickets() to authenticated;
grant execute on function public.admin_update_feedback_ticket(bigint,text,text,text,text) to authenticated;
grant execute on function public.admin_list_game_parties() to authenticated;
grant execute on function public.admin_delete_game_party(bigint,text) to authenticated;

-- 旧后台函数曾继承 PostgreSQL 默认的 PUBLIC EXECUTE；统一收紧为登录后调用，
-- 每个函数内部仍必须通过 public.is_admin() 二次校验。
do $$
declare
  fn record;
begin
  for fn in
    select p.oid::regprocedure::text as signature
    from pg_proc p
    join pg_namespace n on n.oid=p.pronamespace
    where n.nspname='public' and p.proname like 'admin\_%' escape '\'
  loop
    execute format('revoke all on function %s from public, anon, authenticated',fn.signature);
    execute format('grant execute on function %s to authenticated',fn.signature);
  end loop;
end;
$$;

notify pgrst, 'reload schema';
